#!/bin/bash

# Comprehensive Test Suite for reference-data (MS-01) v2.0
# Tests ALL 18 Business Rules (BR-REF-RES-001 .. BR-REF-SEED-007) + the SEED-GEO negative finding.
# ALL tests execute against the running service - ZERO SKIPS.
# Generated by SAAM Framework.
#
# NAMING AUTHORITY: spec/microservices/MS-01/04-api-contract.yaml (OpenAPI 3.1).
#   - Wire fields are snake_case (iso_code, country_iso_code, sort_order, status_code, ...).
#   - Enum values are PascalCase (ProvincesResponse.status = Success | Failure).
#   - Error shape is the shared ErrorResponse: {error, message, status_code}.
#   - NAMES ARE NEVER taken from 01-business-rules.md Concrete Examples (those pre-date the
#     contract and use camelCase such as isoCode/statusCode — the CONTRACT wins).
#
# HEADER EXCEPTION (contract x-global-headers, ADR-006):
#   reference-data is GLOBAL / tenant-neutral. It carries NO x-tenant-id and NO x-store-id.
#   Only x-correlation-id (optional) applies. This suite therefore does NOT send tenant/store headers.
#
# DEPENDENCIES: 05-dependencies.md — reference-data is a read-only leaf provider with NO sync
#   REST dependencies on other services. No dependency mocks are required.

BASE_URL="http://localhost:8001/api/v1/reference"
HEALTH_URL="http://localhost:8001/health"

PASSED=0
FAILED=0
TOTAL=0

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

declare -a FAILED_TESTS

# ============================================
# Global Headers (from API contract x-global-headers — applies to ALL requests)
# ============================================
# reference-data is global/tenant-neutral: NO x-tenant-id / x-store-id (contract exception).
# Only the optional correlation header applies; Content-Type is added on bodied requests.
CORRELATION_HEADER="x-correlation-id: test-corr-001"

# ============================================
# Helper Functions
# ============================================

# Extract a top-level field from JSON response (handles nested objects, ids, string codes).
# Usage: extract_field "$LAST_BODY" "iso_code"
# NEVER use grep for field extraction — nested objects may serialize before the root field.
extract_field() {
    local json=$1
    local field=$2
    if command -v jq &>/dev/null; then
        echo "$json" | jq -r ".$field"
    else
        echo "$json" | python3 -c "import sys,json; print(json.load(sys.stdin)['$field'])"
    fi
}

assert_status() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local expected_status=$7

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected Status: $expected_status"

    if [ -n "$payload" ] && [ "$payload" != "null" ]; then
        actual_status=$(curl -s -o /dev/null -w '%{http_code}' -X "$http_method" "$url" \
            -H 'Content-Type: application/json' -H "$CORRELATION_HEADER" -d "$payload")
    else
        actual_status=$(curl -s -o /dev/null -w '%{http_code}' -X "$http_method" "$url" \
            -H "$CORRELATION_HEADER")
    fi

    if [ "$actual_status" = "$expected_status" ]; then
        echo -e "  ${GREEN}✅ PASSED${NC} (HTTP $actual_status)"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}❌ FAILED${NC} (Expected: $expected_status, Got: $actual_status)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Expected $expected_status, Got $actual_status")
        return 1
    fi
}

assert_json_field() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local json_pattern=$7

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected pattern: $json_pattern"

    if [ -n "$payload" ] && [ "$payload" != "null" ]; then
        result=$(curl -s -X "$http_method" "$url" \
            -H 'Content-Type: application/json' -H "$CORRELATION_HEADER" -d "$payload")
    else
        result=$(curl -s -X "$http_method" "$url" -H "$CORRELATION_HEADER")
    fi

    if echo "$result" | grep -qF "$json_pattern"; then
        echo -e "  ${GREEN}✅ PASSED${NC}"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}❌ FAILED${NC}"
        echo "  Expected pattern: $json_pattern"
        echo "  Got: $(echo "$result" | head -c 300)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Pattern '$json_pattern' not found")
        return 1
    fi
}

assert_json_regex() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local regex=$7

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Regex: $regex"

    if [ -n "$payload" ] && [ "$payload" != "null" ]; then
        result=$(curl -s -X "$http_method" "$url" \
            -H 'Content-Type: application/json' -H "$CORRELATION_HEADER" -d "$payload")
    else
        result=$(curl -s -X "$http_method" "$url" -H "$CORRELATION_HEADER")
    fi

    if echo "$result" | grep -qE "$regex"; then
        echo -e "  ${GREEN}✅ PASSED${NC}"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}❌ FAILED${NC}"
        echo "  Regex not matched: $regex"
        echo "  Got: $(echo "$result" | head -c 300)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Regex '$regex' not matched")
        return 1
    fi
}

# Capture response body for extracting fields.
capture_response() {
    local http_method=$1
    local url=$2
    local payload=$3

    if [ -n "$payload" ] && [ "$payload" != "null" ]; then
        curl -s -X "$http_method" "$url" \
            -H 'Content-Type: application/json' -H "$CORRELATION_HEADER" -d "$payload"
    else
        curl -s -X "$http_method" "$url" -H "$CORRELATION_HEADER"
    fi
}

# Capture BOTH status code AND response body in a single request.
# Usage: capture_with_status "GET" "$URL" ""
# Sets global variables: LAST_STATUS and LAST_BODY.
capture_with_status() {
    local http_method=$1
    local url=$2
    local payload=$3
    local response

    if [ -n "$payload" ] && [ "$payload" != "null" ]; then
        response=$(curl -s -w "\n%{http_code}" -X "$http_method" "$url" \
            -H 'Content-Type: application/json' -H "$CORRELATION_HEADER" -d "$payload")
    else
        response=$(curl -s -w "\n%{http_code}" -X "$http_method" "$url" -H "$CORRELATION_HEADER")
    fi

    LAST_STATUS=$(echo "$response" | tail -1)
    LAST_BODY=$(echo "$response" | sed '$d')
}

# Assert status + capture body in one call (prevents double-request problem).
assert_status_and_capture() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local expected_status=$7

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected Status: $expected_status"

    capture_with_status "$http_method" "$url" "$payload"

    if [ "$LAST_STATUS" = "$expected_status" ]; then
        echo -e "  ${GREEN}✅ PASSED${NC} (HTTP $LAST_STATUS)"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}❌ FAILED${NC} (Expected: $expected_status, Got: $LAST_STATUS)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Expected $expected_status, Got $LAST_STATUS")
        return 1
    fi
}

echo "=============================================="
echo "reference-data (MS-01) - Comprehensive Test Suite v2.0"
echo "ALL 18 Business Rules - ZERO SKIPS"
echo "=============================================="

# Pre-flight check — use the ABSOLUTE health URL (never relative to BASE_URL).
echo -e "${YELLOW}Pre-flight: Checking service availability...${NC}"
if ! curl -s -f "$HEALTH_URL" > /dev/null 2>&1; then
    if ! curl -s -o /dev/null -w '%{http_code}' "$BASE_URL/currencies" | grep -q "200\|401\|403"; then
        echo -e "${RED}ERROR: Service not running at $BASE_URL${NC}"
        exit 1
    fi
fi
echo -e "${GREEN}✓ Service is running at $BASE_URL${NC}"

# Create temp directory for payloads.
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

# ============================================================
# SECTION 1: Group RES — Code / ISO resolution (BR-REF-RES-001..004, 4 rules)
# ============================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 1: RES — Code / ISO resolution (4 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-REF-RES-001: Country resolved by ISO code ---
# Success + response-shape fidelity (contract Country: iso_code, supported, name).
assert_status_and_capture 1 "Resolve country by ISO code (success)" "BR-REF-RES-001" \
    "GET" "$BASE_URL/countries/CA?language=en" "" "200"
assert_json_field 2 "Country carries snake_case iso_code" "BR-REF-RES-001" \
    "GET" "$BASE_URL/countries/CA?language=en" "" '"iso_code":"CA"'
assert_json_field 3 "Country carries snake_case supported flag" "BR-REF-RES-001" \
    "GET" "$BASE_URL/countries/CA?language=en" "" '"supported":'
# Error case: unknown code -> 404 (contract NotFound), NOT 500.
assert_status 4 "Unknown country ISO code returns 404" "BR-REF-RES-001" \
    "GET" "$BASE_URL/countries/ZZ" "" "404"
# Error-shape fidelity: shared ErrorResponse uses snake_case status_code (NOT statusCode).
assert_json_field 5 "404 body uses shared ErrorResponse status_code (snake_case)" "BR-REF-RES-001" \
    "GET" "$BASE_URL/countries/ZZ" "" '"status_code":404'

# --- BR-REF-RES-002: Language resolved by language code ---
assert_status 6 "Resolve language by code (success)" "BR-REF-RES-002" \
    "GET" "$BASE_URL/languages/en" "" "200"
assert_json_field 7 "Language carries code field" "BR-REF-RES-002" \
    "GET" "$BASE_URL/languages/en" "" '"code":"en"'
assert_status 8 "Unknown language code returns 404" "BR-REF-RES-002" \
    "GET" "$BASE_URL/languages/xx" "" "404"

# --- BR-REF-RES-003: Currency resolved by currency code (uncached) ---
assert_status 9 "Resolve currency by code (success)" "BR-REF-RES-003" \
    "GET" "$BASE_URL/currencies/USD" "" "200"
assert_json_field 10 "Currency carries code field" "BR-REF-RES-003" \
    "GET" "$BASE_URL/currencies/USD" "" '"code":"USD"'
assert_status 11 "Unknown currency code returns 404" "BR-REF-RES-003" \
    "GET" "$BASE_URL/currencies/ABC" "" "404"

# --- BR-REF-RES-004: Zone resolved by globally-unique zone code ---
assert_status 12 "Resolve zone by code (success)" "BR-REF-RES-004" \
    "GET" "$BASE_URL/zones/QC" "" "200"
assert_json_field 13 "Zone carries snake_case country_iso_code (INV-REF-004)" "BR-REF-RES-004" \
    "GET" "$BASE_URL/zones/QC" "" '"country_iso_code":'
assert_status 14 "Unknown zone code returns 404" "BR-REF-RES-004" \
    "GET" "$BASE_URL/zones/ZZ" "" "404"

# ============================================================
# SECTION 2: Group LST — Localized, name-sorted reference lists (BR-REF-LST-001..006, 6 rules)
# ============================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 2: LST — Localized name-sorted lists (6 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-REF-LST-001: Countries listed in one language, name-sorted, localized names ---
# Success + response-shape fidelity: list envelope { items: [...] }.
assert_status 15 "List countries for a language (success)" "BR-REF-LST-001" \
    "GET" "$BASE_URL/countries?language=en" "" "200"
assert_json_field 16 "Country list uses items[] envelope" "BR-REF-LST-001" \
    "GET" "$BASE_URL/countries?language=en" "" '"items":'
assert_json_field 17 "Listed country carries localized name" "BR-REF-LST-001" \
    "GET" "$BASE_URL/countries?language=en" "" '"name":'
# Required-parameter omission (negative): language is required -> contract 400, NOT 500.
assert_status 18 "Omitting required 'language' param returns 400" "BR-REF-LST-001" \
    "GET" "$BASE_URL/countries" "" "400"
# Fail-soft (BR-REF-CAC-002): unknown language yields 200 with empty items, never an error.
assert_status_and_capture 19 "Unknown language list is fail-soft 200" "BR-REF-LST-001" \
    "GET" "$BASE_URL/countries?language=zz" "" "200"
assert_json_field 20 "Unknown language yields empty items[] (fail-soft)" "BR-REF-LST-001" \
    "GET" "$BASE_URL/countries?language=zz" "" '"items":[]'

# --- BR-REF-LST-002: Zones listed by country + language, name-sorted, localized ---
assert_status 21 "List a country's zones for a language (success)" "BR-REF-LST-002" \
    "GET" "$BASE_URL/countries/CA/zones?language=en" "" "200"
assert_json_field 22 "Zone list uses items[] envelope" "BR-REF-LST-002" \
    "GET" "$BASE_URL/countries/CA/zones?language=en" "" '"items":'
assert_status 23 "Country zones omitting required 'language' returns 400" "BR-REF-LST-002" \
    "GET" "$BASE_URL/countries/CA/zones" "" "400"
assert_json_field 24 "Unknown language zones are fail-soft empty items[]" "BR-REF-LST-002" \
    "GET" "$BASE_URL/countries/CA/zones?language=zz" "" '"items":[]'

# --- BR-REF-LST-003: All seeded languages listed (code-keyed) ---
assert_status 25 "List all languages (success)" "BR-REF-LST-003" \
    "GET" "$BASE_URL/languages" "" "200"
assert_json_field 26 "Languages list uses items[] envelope" "BR-REF-LST-003" \
    "GET" "$BASE_URL/languages" "" '"items":'
# Language entry carries snake_case sort_order per contract (NOT sortOrder).
assert_json_field 27 "Language entry carries snake_case sort_order field" "BR-REF-LST-003" \
    "GET" "$BASE_URL/languages" "" '"sort_order"'

# --- BR-REF-LST-004: Country map is insertion-ordered by ISO code (as=Map) ---
# 'as' is optional (default List). Optional-param omission MUST succeed (List form).
assert_status 28 "Country list with 'as' omitted defaults to List (success)" "BR-REF-LST-004" \
    "GET" "$BASE_URL/countries?language=en" "" "200"
# Explicit Map form (contract enum value 'Map', PascalCase).
assert_status 29 "Country list as=Map returns 200" "BR-REF-LST-004" \
    "GET" "$BASE_URL/countries?language=en&as=Map" "" "200"
# Invalid enum value for 'as' -> contract 400.
assert_status 30 "Invalid 'as' value returns 400" "BR-REF-LST-004" \
    "GET" "$BASE_URL/countries?language=en&as=Tree" "" "400"

# --- BR-REF-LST-005: Countries filtered to a requested subset of ISO codes ---
# Query param name is snake_case 'iso_codes' (contract), NOT the BR-example 'isoCodes'.
assert_status_and_capture 31 "Filter countries to iso_codes subset (success)" "BR-REF-LST-005" \
    "GET" "$BASE_URL/countries?language=en&iso_codes=CA,US,MX" "" "200"
assert_json_field 32 "Subset filter returns items[] envelope" "BR-REF-LST-005" \
    "GET" "$BASE_URL/countries?language=en&iso_codes=CA,US,MX" "" '"items":'
# Empty subset yields fail-soft empty list (200, not error).
assert_json_field 33 "Empty iso_codes subset yields empty items[]" "BR-REF-LST-005" \
    "GET" "$BASE_URL/countries?language=en&iso_codes=" "" '"items":[]'

# --- BR-REF-LST-006: Currencies listed ordered by currency code ---
assert_status 34 "List all currencies (success)" "BR-REF-LST-006" \
    "GET" "$BASE_URL/currencies" "" "200"
assert_json_field 35 "Currency list uses items[] envelope" "BR-REF-LST-006" \
    "GET" "$BASE_URL/currencies" "" '"items":'
assert_json_field 36 "Listed currency carries code and name fields" "BR-REF-LST-006" \
    "GET" "$BASE_URL/currencies" "" '"code":'

# ============================================================
# SECTION 3: Group CAC — Caching behavior (BR-REF-CAC-001..002, 2 rules)
# ============================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 3: CAC — Caching behavior (2 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-REF-CAC-001: Reference lists memoized (read-through) — second read matches first ---
# Behavioral: two successive reads return the same payload (cache does not alter the result).
capture_with_status "GET" "$BASE_URL/countries?language=en" ""
CAC_FIRST_STATUS="$LAST_STATUS"
CAC_FIRST_BODY="$LAST_BODY"
capture_with_status "GET" "$BASE_URL/countries?language=en" ""
CAC_SECOND_BODY="$LAST_BODY"
TOTAL=$((TOTAL + 1))
echo -e "\n${BLUE}Test 37: Cached list is stable across successive reads${NC}"
echo -e "  Rule: BR-REF-CAC-001 | Expected: identical body on repeat read"
if [ "$CAC_FIRST_STATUS" = "200" ] && [ "$CAC_FIRST_BODY" = "$CAC_SECOND_BODY" ]; then
    echo -e "  ${GREEN}✅ PASSED${NC}"
    PASSED=$((PASSED + 1))
else
    echo -e "  ${RED}❌ FAILED${NC} (status $CAC_FIRST_STATUS; bodies differ across cached reads)"
    FAILED=$((FAILED + 1))
    FAILED_TESTS+=("Test 37: Cached list stable [BR-REF-CAC-001] - repeat read differed")
fi

# --- BR-REF-CAC-002: List/lookup failures are swallowed -> empty result, never a thrown error ---
# Fail-soft contract: an unresolvable list returns 200 with empty items, never 5xx.
assert_status 38 "Fail-soft: unresolvable list never returns 5xx" "BR-REF-CAC-002" \
    "GET" "$BASE_URL/countries?language=zz" "" "200"
assert_json_field 39 "Fail-soft envelope carries empty items[] not an error" "BR-REF-CAC-002" \
    "GET" "$BASE_URL/countries?language=zz" "" '"items":[]'
# The provinces endpoint fail-soft: assert the {status, items} envelope (NOT an error) on bad country.
assert_status_and_capture 40 "Provinces fail-soft on unknown country is 200" "BR-REF-CAC-002" \
    "POST" "$BASE_URL/provinces" '{"country_code":"ZZ"}' "200"
assert_json_field 41 "Provinces fail-soft returns Failure status + empty items[]" "BR-REF-CAC-002" \
    "POST" "$BASE_URL/provinces" '{"country_code":"ZZ"}' '"status":"Failure"'

# ============================================================
# SECTION 4: Group LNG — Language / locale conversion and defaulting (BR-REF-LNG-001..003, 3 rules)
# ============================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 4: LNG — Language / locale resolution (3 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-REF-LNG-001: Language -> locale using its code as the language tag ---
# Exercised through the province lookup path which drives locale-based localized names.
# A valid language on a valid country resolves and localizes -> SUCCESS envelope.
assert_json_field 42 "Language code drives localized province lookup (locale build)" "BR-REF-LNG-001" \
    "POST" "$BASE_URL/provinces" '{"country_code":"CA","lang":"fr"}' '"status":"Success"'

# --- BR-REF-LNG-002: Locale maps back to a configured language, or 204 if unsupported ---
assert_status 43 "Resolve configured locale to a language (success)" "BR-REF-LNG-002" \
    "GET" "$BASE_URL/languages/resolve?locale=en_US" "" "200"
assert_json_field 44 "Resolved language carries code field" "BR-REF-LNG-002" \
    "GET" "$BASE_URL/languages/resolve?locale=en_US" "" '"code":'
# Unsupported locale -> 204 No Content (contract), never an error.
assert_status 45 "Unsupported locale resolves to 204 No Content" "BR-REF-LNG-002" \
    "GET" "$BASE_URL/languages/resolve?locale=de_DE" "" "204"
# Required-parameter omission: 'locale' is required -> contract 400.
assert_status 46 "Omitting required 'locale' param returns 400" "BR-REF-LNG-002" \
    "GET" "$BASE_URL/languages/resolve" "" "400"

# --- BR-REF-LNG-003: Storefront language defaults to English when none can be resolved ---
# No lang anywhere -> defaults to English, still resolves the province list (SUCCESS).
assert_status_and_capture 47 "Provinces with no language defaults to English (success)" "BR-REF-LNG-003" \
    "POST" "$BASE_URL/provinces" '{"country_code":"CA"}' "200"
assert_json_field 48 "Defaulting to English yields Success status" "BR-REF-LNG-003" \
    "POST" "$BASE_URL/provinces" '{"country_code":"CA"}' '"status":"Success"'
# Unknown lang silently degrades to English (defaulting never errors).
assert_json_field 49 "Unknown lang silently falls back to English (Success)" "BR-REF-LNG-003" \
    "POST" "$BASE_URL/provinces" '{"country_code":"CA","lang":"zz"}' '"status":"Success"'

# ============================================================
# SECTION 5: Group API — Reference endpoints (BR-REF-API-001..003, 3 rules)
# ============================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 5: API — Reference endpoints (3 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-REF-API-001: Provinces endpoint returns localized zones for address forms, fail-soft ---
# Success path + response-shape fidelity: domain-specific {status, items} fail-soft envelope.
assert_status_and_capture 50 "Provinces lookup for a known country (success)" "BR-REF-API-001" \
    "POST" "$BASE_URL/provinces" '{"country_code":"CA","lang":"en"}' "200"
assert_json_field 51 "Provinces success status is PascalCase 'Success'" "BR-REF-API-001" \
    "POST" "$BASE_URL/provinces" '{"country_code":"CA","lang":"en"}' '"status":"Success"'
assert_json_field 52 "Provinces envelope carries items[] of entries" "BR-REF-API-001" \
    "POST" "$BASE_URL/provinces" '{"country_code":"CA","lang":"en"}' '"items":'
# Required-body-field omission: country_code is required -> contract 400 (BadRequest), NOT 500.
assert_status 53 "Provinces missing required country_code returns 400" "BR-REF-API-001" \
    "POST" "$BASE_URL/provinces" '{"lang":"en"}' "400"

# --- BR-REF-API-002: Name lookups echo the code when a display name cannot be resolved ---
# Success: known country name resolves; response-shape fidelity: NameResponse { value }.
assert_status_and_capture 54 "Country name lookup resolves localized name" "BR-REF-API-002" \
    "GET" "$BASE_URL/countries/CA/name?language=en" "" "200"
assert_json_field 55 "Name lookup returns NameResponse value field" "BR-REF-API-002" \
    "GET" "$BASE_URL/countries/CA/name?language=en" "" '"value":'
# Fallback: unknown country name echoes the input code (200, never 404 for this endpoint).
assert_status_and_capture 56 "Unknown country name echoes code, stays 200" "BR-REF-API-002" \
    "GET" "$BASE_URL/countries/ZZ/name?language=en" "" "200"
assert_json_field 57 "Unknown country name echoes the input code as value" "BR-REF-API-002" \
    "GET" "$BASE_URL/countries/ZZ/name?language=en" "" '"value":"ZZ"'
# Zone name variant shares the echo-the-code fallback behavior.
assert_json_field 58 "Unknown zone name echoes the input code as value" "BR-REF-API-002" \
    "GET" "$BASE_URL/zones/ZZ/name?language=en" "" '"value":"ZZ"'
# Optional-param omission: language optional on name endpoints -> still 200.
assert_status 59 "Country name with 'language' omitted still succeeds (200)" "BR-REF-API-002" \
    "GET" "$BASE_URL/countries/CA/name" "" "200"

# --- BR-REF-API-003: Credit-card expiry option lists (years, months) generated and cached ---
# Years list: response-shape fidelity StringListResponse { items:[...] } + behavioral count (10 entries).
assert_status_and_capture 60 "Credit-card years list (success)" "BR-REF-API-003" \
    "GET" "$BASE_URL/credit-card-years" "" "200"
assert_json_field 61 "Credit-card years use StringListResponse items[] envelope" "BR-REF-API-003" \
    "GET" "$BASE_URL/credit-card-years" "" '"items":'
# Behavioral: exactly 10 consecutive years -> items length is 10 (not a placeholder/empty stub).
TOTAL=$((TOTAL + 1))
echo -e "\n${BLUE}Test 62: Credit-card years contains exactly 10 entries${NC}"
echo -e "  Rule: BR-REF-API-003 | Expected: items length == 10"
capture_with_status "GET" "$BASE_URL/credit-card-years" ""
YEARS_COUNT=$(echo "$LAST_BODY" | jq -r '.items | length' 2>/dev/null)
if [ "$YEARS_COUNT" = "10" ]; then
    echo -e "  ${GREEN}✅ PASSED${NC} (10 years)"
    PASSED=$((PASSED + 1))
else
    echo -e "  ${RED}❌ FAILED${NC} (Expected 10 year entries, got: $YEARS_COUNT)"
    FAILED=$((FAILED + 1))
    FAILED_TESTS+=("Test 62: Credit-card years count [BR-REF-API-003] - Expected 10, got $YEARS_COUNT")
fi
# Months list: response-shape + behavioral count (12 two-digit strings).
assert_status_and_capture 63 "Months-of-year list (success)" "BR-REF-API-003" \
    "GET" "$BASE_URL/months-of-year" "" "200"
assert_json_field 64 "Months use StringListResponse items[] envelope" "BR-REF-API-003" \
    "GET" "$BASE_URL/months-of-year" "" '"items":'
TOTAL=$((TOTAL + 1))
echo -e "\n${BLUE}Test 65: Months-of-year contains exactly 12 two-digit entries${NC}"
echo -e "  Rule: BR-REF-API-003 | Expected: items length == 12, first == '01'"
capture_with_status "GET" "$BASE_URL/months-of-year" ""
MONTHS_COUNT=$(echo "$LAST_BODY" | jq -r '.items | length' 2>/dev/null)
MONTHS_FIRST=$(echo "$LAST_BODY" | jq -r '.items[0]' 2>/dev/null)
if [ "$MONTHS_COUNT" = "12" ] && [ "$MONTHS_FIRST" = "01" ]; then
    echo -e "  ${GREEN}✅ PASSED${NC} (12 months, first '01')"
    PASSED=$((PASSED + 1))
else
    echo -e "  ${RED}❌ FAILED${NC} (Expected 12 months first '01', got count=$MONTHS_COUNT first=$MONTHS_FIRST)"
    FAILED=$((FAILED + 1))
    FAILED_TESTS+=("Test 65: Months count/first [BR-REF-API-003] - Expected 12/'01', got $MONTHS_COUNT/$MONTHS_FIRST")
fi

# ============================================================
# SECTION 6: Group SEED — One-time database bootstrap (BR-REF-SEED-001..007, 7 rules)
# ============================================================
# The seed runs once at startup (Empty -> Seeded, terminal). The suite asserts the OBSERVABLE
# EFFECTS of a completed seed through the read API — the only surface a running service exposes.
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 6: SEED — One-time bootstrap effects (7 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-REF-SEED-001: Seeded only when DB empty (guard) — effect: DB is populated, not empty ---
# State-model effect: after bootstrap the aggregate is Seeded, so reference data exists.
assert_status_and_capture 66 "Post-seed: languages exist (Seeded state, not Empty)" "BR-REF-SEED-001" \
    "GET" "$BASE_URL/languages" "" "200"
TOTAL=$((TOTAL + 1))
echo -e "\n${BLUE}Test 67: Post-seed language count > 0 (guard latched to Seeded)${NC}"
echo -e "  Rule: BR-REF-SEED-001 | Expected: items length >= 1"
capture_with_status "GET" "$BASE_URL/languages" ""
LANG_COUNT=$(echo "$LAST_BODY" | jq -r '.items | length' 2>/dev/null)
if [ -n "$LANG_COUNT" ] && [ "$LANG_COUNT" -ge 1 ] 2>/dev/null; then
    echo -e "  ${GREEN}✅ PASSED${NC} ($LANG_COUNT languages)"
    PASSED=$((PASSED + 1))
else
    echo -e "  ${RED}❌ FAILED${NC} (Expected >=1 language after seed, got: $LANG_COUNT)"
    FAILED=$((FAILED + 1))
    FAILED_TESTS+=("Test 67: Post-seed language count [BR-REF-SEED-001] - Expected >=1, got $LANG_COUNT")
fi

# --- BR-REF-SEED-002: Full seed is one ordered, all-or-nothing transaction ---
# Atomic-order effect: dependent data present together — countries (need languages) AND their
# zones (need countries) AND currencies all resolved => the transaction committed as a whole.
assert_status 68 "Atomic seed: seeded country resolvable (languages+countries committed)" "BR-REF-SEED-002" \
    "GET" "$BASE_URL/countries/CA?language=en" "" "200"
assert_json_field 69 "Atomic seed: seeded country's zones present (countries+zones committed)" "BR-REF-SEED-002" \
    "GET" "$BASE_URL/countries/CA/zones?language=en" "" '"items":'
assert_json_field 70 "Atomic seed: currencies present (currencies committed in same tx)" "BR-REF-SEED-002" \
    "GET" "$BASE_URL/currencies" "" '"items":'

# --- BR-REF-SEED-003: Out-of-the-box languages are English and French ---
assert_json_field 71 "Seed effect: English language present" "BR-REF-SEED-003" \
    "GET" "$BASE_URL/languages/en" "" '"code":"en"'
assert_json_field 72 "Seed effect: French language present" "BR-REF-SEED-003" \
    "GET" "$BASE_URL/languages/fr" "" '"code":"fr"'

# --- BR-REF-SEED-004a: Countries seeded from fixed ISO list (localizable ones only) ---
# Effect: a localizable ISO from the catalog exists with a localized description.
assert_status 73 "Seed effect: catalog country (CA) was created" "BR-REF-SEED-004a" \
    "GET" "$BASE_URL/countries/CA?language=en" "" "200"
assert_json_field 74 "Seed effect: created country has a localized name in a configured language" "BR-REF-SEED-004a" \
    "GET" "$BASE_URL/countries/CA?language=en" "" '"name":'

# --- BR-REF-SEED-004: Zones seeded from country/language catalog ---
# Effect: a catalog zone (QC) exists and is linked to its country (CA).
assert_status_and_capture 75 "Seed effect: catalog zone (QC) was created" "BR-REF-SEED-004" \
    "GET" "$BASE_URL/zones/QC" "" "200"
assert_json_field 76 "Seed effect: zone linked to its country via country_iso_code" "BR-REF-SEED-004" \
    "GET" "$BASE_URL/zones/QC" "" '"country_iso_code":"CA"'

# --- BR-REF-SEED-005: Currencies seeded from catalog (platform-rejected codes skipped) ---
# Effect: a valid ISO-4217 currency (USD) exists and is marked supported.
assert_status_and_capture 77 "Seed effect: catalog currency (USD) was created" "BR-REF-SEED-005" \
    "GET" "$BASE_URL/currencies/USD" "" "200"
assert_json_field 78 "Seed effect: seeded currency is marked supported" "BR-REF-SEED-005" \
    "GET" "$BASE_URL/currencies/USD" "" '"supported":true'

# --- BR-REF-SEED-006: Default store + tax class MOVED OUT of MS-01 (boundary decision) ---
# reference-data owns ONLY geo/currency/language data — it exposes NO merchant-store resource.
# Assert the store resource is NOT a reference-data resource (404 — not served here).
assert_status 79 "Moved-out: reference-data exposes no merchant-store resource (404)" "BR-REF-SEED-006" \
    "GET" "$BASE_URL/stores/DEFAULT" "" "404"

# --- BR-REF-SEED-007: Product type + integration modules MOVED OUT of MS-01 ---
# reference-data exposes NO integration-modules / product-type resource (owned by catalog/system-config).
assert_status 80 "Moved-out: reference-data exposes no integration-modules resource (404)" "BR-REF-SEED-007" \
    "GET" "$BASE_URL/integration-modules" "" "404"

# ============================================================
# SECTION 7: Negative finding — BR-REF-SEED-GEO (geo-zones modeled, never populated, no endpoint)
# ============================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 7: SEED-GEO — geo-zone absence (negative finding)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# The target ships geo-zone tables EMPTY and exposes NO geo-zone endpoint until genuinely built.
# Assert the absence is honored: no geo-zone resource is served by reference-data.
assert_status 81 "Geo-zone resource is intentionally not exposed (404)" "BR-REF-SEED-GEO" \
    "GET" "$BASE_URL/geo-zones" "" "404"

# ============================================
# SUMMARY
# ============================================
echo ""
echo "================================================================"
echo "TEST SUMMARY"
echo "================================================================"
echo ""
echo -e "${CYAN}Total Tests:  $TOTAL${NC}"
echo -e "${GREEN}Passed:       $PASSED${NC}"
echo -e "${RED}Failed:       $FAILED${NC}"
echo ""

if [ $FAILED -gt 0 ]; then
    echo -e "${RED}Failed Tests:${NC}"
    for test in "${FAILED_TESTS[@]}"; do
        echo "  ✗ $test"
    done
    echo ""
fi

if [ $TOTAL -gt 0 ]; then
    echo "Success Rate: $((PASSED * 100 / TOTAL))%"
fi

echo ""
if [ $FAILED -eq 0 ]; then
    echo -e "${GREEN}✅ ALL $TOTAL TESTS PASSED — 100% SUCCESS${NC}"
    exit 0
else
    echo -e "${RED}❌ $FAILED OF $TOTAL TESTS FAILED${NC}"
    exit 1
fi
