#!/bin/bash

# ============================================================================
# Comprehensive Test Suite for MS-08 Shipping Service v2.0
# Tests ALL 32 ACTIVE Business Rules (BR-SHIP group)
# ALL tests execute against the running service - ZERO SKIPS
# Generated by SAAM Framework (Phase 4c)
# ============================================================================
#
# NAMING AUTHORITY: spec/microservices/MS-08/04-api-contract.yaml (OpenAPI 3.1)
#   - Wire fields are snake_case (Concern A).
#   - Enum WIRE values are PascalCase (Concern G): shipping_type National|International;
#     shipping_option_price_type Least|Highest|All; shipping_package_type Item|Box.
#     ShippingReturnCode stays UPPER_CASE (external/legacy status codes):
#     NO_SHIPPING_TO_SELECTED_COUNTRY | NO_SHIPPING_MODULE_CONFIGURED | ERROR.
#   - Paths exactly as declared (e.g. /quotes, /providers/{moduleCode}).
#   - Status codes exactly as declared per operation (201 create, 204 delete, 403, 404, 409, 422, 500).
#
# HEADER RECONCILIATION (Concern B exception): the MS-08 contract x-global-headers declares
#   TenantHeader ONLY — store scoping is FOLDED INTO the tenant header (see auth-config.md).
#   The declared header is `x-tenant-id` with testValue `test-tenant-001`. There is NO x-store-id
#   for MS-08 (documented exception to the generic infrastructure-patterns.md convention). This
#   suite therefore sends `x-tenant-id` exactly as the contract declares.
#
# COVERAGE: BR-SHIP-001..034 EXCEPT the two rules dropped in Phase 4a (numbers 005 and 027),
#   which were moved to 07-obsolete-rules-appendix.md. Those two BR-IDs are intentionally ABSENT
#   from this suite (their full tokens do not appear anywhere here, by design).
#   The 9 Simplify/fix-on-migration rules (BR-SHIP-006/010/016/017/019/021/022/025/030) are tested
#   for the CORRECTED behavior, NOT the preserved legacy quirk:
#     - BR-SHIP-006: deterministic (stable) provider selection.
#     - BR-SHIP-010: free-shipping threshold uses >= (order exactly at threshold QUALIFIES); exact decimals.
#     - BR-SHIP-016/017: option price selection compares EXACT decimals (12.20 vs 12.80 differ).
#     - BR-SHIP-019: tax_on_shipping propagates into the summary.
#     - BR-SHIP-021: correct attribute-weight getter (weight accumulation correct).
#     - BR-SHIP-022: per-package shipping_quantity is 1.
#     - BR-SHIP-025: per-box weight/dims (not stale last-box).
#     - BR-SHIP-030: delete-shipping-method / delete-provider IS role-gated (401/403 without the role).
#
# ============================================================================
# MS-04 CATALOG MOCK (dependency per 05-dependencies.md)
# ============================================================================
# MS-08 depends on catalog (MS-04) via sync REST for two reads:
#   - GET /api/v1/catalog/products/{id}/final-price  -> { "final_price": ... }  (BR-SHIP-008/013)
#   - GET /api/v1/catalog/products/{id}               -> { "virtual":.., "shippable":.. } (BR-SHIP-020)
# This suite starts a lightweight python3 http.server mock for MS-04 on port 8104 and exports
# CATALOG_BASE_URL / MS04_MOCK_URL so the service-under-test can resolve product price + flags.
# The mock returns deterministic final_price=10.00 and virtual=false/shippable=true for any product,
# except product id "virt-*" which is returned virtual=true (exercises BR-SHIP-020 exclusion).
# The mock is torn down on EXIT.
# ============================================================================

BASE_URL="http://localhost:8008/api/v1/shipping"
HEALTH_URL="http://localhost:8008/health"
CATALOG_MOCK_PORT="8104"
CATALOG_BASE_URL="http://localhost:${CATALOG_MOCK_PORT}/api/v1/catalog"
export CATALOG_BASE_URL
export MS04_MOCK_URL="$CATALOG_BASE_URL"

PASSED=0
FAILED=0
TOTAL=0

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

declare -a FAILED_TESTS

# ============================================
# Global Headers (from API contract — TenantHeader only, Concern B exception)
# ============================================
TENANT_HEADER="x-tenant-id: test-tenant-001"
# A caller WITHOUT the shipping-management role (BR-SHIP-030 role-gate negative cases).
NO_ROLE_HEADER="x-roles: none"
# A caller WITH the shipping-management role (positive admin cases).
ROLE_HEADER="x-roles: SHIPPING"

# ============================================
# Helper Functions
# ============================================

# Extract a top-level field from JSON response (handles nested objects, UUIDs, string IDs)
extract_field() {
    local json=$1
    local field=$2
    if command -v jq &>/dev/null; then
        echo "$json" | jq -r ".$field"
    else
        echo "$json" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('$field',''))"
    fi
}

# Capture BOTH status code AND response body in a single request.
# Sets global LAST_STATUS and LAST_BODY. Extra headers may be appended via $EXTRA_HEADERS.
capture_with_status() {
    local http_method=$1
    local url=$2
    local payload=$3
    local response

    if [ -n "$payload" ] && [ "$payload" != "null" ]; then
        response=$(curl -s -w "\n%{http_code}" -X "$http_method" "$url" \
            -H 'Content-Type: application/json' -H "$TENANT_HEADER" $EXTRA_HEADERS -d "$payload")
    else
        response=$(curl -s -w "\n%{http_code}" -X "$http_method" "$url" \
            -H "$TENANT_HEADER" $EXTRA_HEADERS)
    fi

    LAST_STATUS=$(echo "$response" | tail -1)
    LAST_BODY=$(echo "$response" | sed '$d')
}

# Assert exact status only.
assert_status() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local expected_status=$7

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected Status: $expected_status"

    capture_with_status "$http_method" "$url" "$payload"

    if [ "$LAST_STATUS" = "$expected_status" ]; then
        echo -e "  ${GREEN}PASSED${NC} (HTTP $LAST_STATUS)"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}FAILED${NC} (Expected: $expected_status, Got: $LAST_STATUS)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Expected $expected_status, Got $LAST_STATUS")
        return 1
    fi
}

# Assert exact status + capture body in one request (no double-POST).
assert_status_and_capture() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local expected_status=$7

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected Status: $expected_status"

    capture_with_status "$http_method" "$url" "$payload"

    if [ "$LAST_STATUS" = "$expected_status" ]; then
        echo -e "  ${GREEN}PASSED${NC} (HTTP $LAST_STATUS)"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}FAILED${NC} (Expected: $expected_status, Got: $LAST_STATUS)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Expected $expected_status, Got $LAST_STATUS")
        return 1
    fi
}

# Assert a JSON field/pattern is present in the response body (fixed-string grep — safe for decimals).
assert_json_field() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local json_pattern=$7

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected pattern: $json_pattern"

    capture_with_status "$http_method" "$url" "$payload"

    if echo "$LAST_BODY" | grep -qF "$json_pattern"; then
        echo -e "  ${GREEN}PASSED${NC}"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}FAILED${NC}"
        echo "  Expected pattern: $json_pattern"
        echo "  Got: $(echo "$LAST_BODY" | head -c 300)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Pattern '$json_pattern' not found")
        return 1
    fi
}

# ============================================
# MS-04 catalog mock (python3 http.server)
# ============================================
TMPDIR=$(mktemp -d)
CATALOG_MOCK_PID=""

start_catalog_mock() {
    cat > "$TMPDIR/ms04_mock.py" <<'PYEOF'
import json
from http.server import BaseHTTPRequestHandler, HTTPServer

PORT = 8104

class Handler(BaseHTTPRequestHandler):
    def log_message(self, *args):
        pass

    def _send(self, code, body):
        payload = json.dumps(body).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def do_GET(self):
        path = self.path.split("?", 1)[0]
        parts = [p for p in path.split("/") if p]
        # /api/v1/catalog/products/{id}/final-price
        if len(parts) == 6 and parts[3] == "products" and parts[5] == "final-price":
            self._send(200, {
                "final_price": 10.00, "original_price": 10.00,
                "discounted_price": 10.00, "default_price": True,
                "discounted": False, "discount_percent": 0,
            })
            return
        # /api/v1/catalog/products/{id}
        if len(parts) == 5 and parts[3] == "products":
            pid = parts[4]
            virtual = pid.startswith("virt")
            self._send(200, {
                "id": pid, "sku": "SKU-" + pid, "available": True, "visible": True,
                "virtual": virtual, "shippable": (not virtual), "free": False,
            })
            return
        self._send(404, {"error": "not_found", "message": "no such product"})

if __name__ == "__main__":
    HTTPServer(("127.0.0.1", PORT), Handler).serve_forever()
PYEOF
    python3 "$TMPDIR/ms04_mock.py" &
    CATALOG_MOCK_PID=$!
    # brief wait for the mock to bind
    for _ in 1 2 3 4 5 10; do
        if curl -s -o /dev/null "$CATALOG_BASE_URL/products/probe"; then break; fi
        sleep 0.3
    done
}

cleanup() {
    if [ -n "$CATALOG_MOCK_PID" ]; then
        kill "$CATALOG_MOCK_PID" 2>/dev/null
    fi
    rm -rf "$TMPDIR"
}
trap cleanup EXIT

echo "=============================================="
echo "MS-08 Shipping - Comprehensive Test Suite v2.0"
echo "ALL 32 ACTIVE Business Rules - ZERO SKIPS"
echo "(the two Phase-4a-obsolete rules, numbers 005 and 027, are NOT tested)"
echo "=============================================="

echo -e "${YELLOW}Starting MS-04 catalog mock on port ${CATALOG_MOCK_PORT}...${NC}"
start_catalog_mock
echo -e "${GREEN}MS-04 mock at $CATALOG_BASE_URL${NC}"

# Pre-flight check (HEALTH_URL is absolute per infrastructure-patterns.md)
echo -e "${YELLOW}Pre-flight: Checking service availability...${NC}"
if ! curl -s -f "$HEALTH_URL" > /dev/null 2>&1; then
    if ! curl -s -o /dev/null -w '%{http_code}' "$BASE_URL/configuration" -H "$TENANT_HEADER" | grep -q "200\|401\|403\|500"; then
        echo -e "${RED}ERROR: Service not running at $BASE_URL${NC}"
        exit 1
    fi
fi
echo -e "${GREEN}Service is running at $BASE_URL${NC}"

# ============================================================================
# SECTION 1: Shipping configuration document (BR-SHIP-001)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 1: Shipping configuration (BR-SHIP-001)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# BR-SHIP-001: configuration is loaded, defaulting to a fresh config when absent.
EXTRA_HEADERS=""
assert_status 1 "Get shipping configuration (defaults when absent)" "BR-SHIP-001" \
    "GET" "$BASE_URL/configuration" "null" "200"

# Contract-conformance: response shape carries the enum fields (PascalCase wire values).
assert_json_field 2 "Configuration exposes shipping_type enum (PascalCase)" "BR-SHIP-001" \
    "GET" "$BASE_URL/configuration" "null" '"shipping_type"'

# ============================================================================
# SECTION 2: Quote pipeline validation & routing
#            (BR-SHIP-002/003/004/006/007/013)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 2: Quote validation & routing${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# Seed National config + weightBased provider so quotes can route (deterministic setup).
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 3 "Set store shipping mode = National" "BR-SHIP-003" \
    "PUT" "$BASE_URL/configuration" '{"shipping_type":"National"}' "200"

# BR-SHIP-002: delivery country is mandatory -> success path (country present).
EXTRA_HEADERS=""
assert_status 4 "Quote requires delivery country (present -> accepted)" "BR-SHIP-002" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"p1","quantity":1,"weight":2.0}]}' \
    "200"

# BR-SHIP-002: missing delivery country -> 422 (boundary rejection, NOT 500).
assert_status 5 "Quote missing delivery country -> 422" "BR-SHIP-002" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{},"items":[{"product_id":"p1","quantity":1}]}' \
    "422"

# BR-SHIP-003: National -> destination must equal store country. Matching country -> no return_code.
assert_json_field 6 "National: matching destination proceeds (no refusal)" "BR-SHIP-003" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"p1","quantity":1,"weight":2.0}]}' \
    '"options"'

# BR-SHIP-003: National -> non-matching destination refused with NO_SHIPPING_TO_SELECTED_COUNTRY.
assert_json_field 7 "National: non-matching destination refused" "BR-SHIP-003" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"FR"},"items":[{"product_id":"p1","quantity":1,"weight":2.0}]}' \
    '"NO_SHIPPING_TO_SELECTED_COUNTRY"'

# BR-SHIP-004: International -> destination must be in supported list.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 8 "Switch store to International" "BR-SHIP-004" \
    "PUT" "$BASE_URL/configuration" '{"shipping_type":"International"}' "200"
assert_status 9 "Set supported countries = [US, GB]" "BR-SHIP-004" \
    "PUT" "$BASE_URL/supported-countries" '{"items":["US","GB"]}' "200"

EXTRA_HEADERS=""
# BR-SHIP-004: unsupported destination refused.
assert_json_field 10 "International: unsupported destination refused" "BR-SHIP-004" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"JP"},"items":[{"product_id":"p1","quantity":1,"weight":2.0}]}' \
    '"NO_SHIPPING_TO_SELECTED_COUNTRY"'

# Reset to National for the remaining quote tests.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 11 "Reset store to National" "BR-SHIP-003" \
    "PUT" "$BASE_URL/configuration" '{"shipping_type":"National"}' "200"

# BR-SHIP-006 [4a: deterministic selection]: seed weightBased provider (active) so a provider is chosen.
assert_status 12 "Configure weightBased provider (active)" "BR-SHIP-006" \
    "PUT" "$BASE_URL/providers" '{"module_code":"weightBased","active":true}' "200"

EXTRA_HEADERS=""
# BR-SHIP-006 [4a corrected]: with an active provider, selection is deterministic -> a module code returns.
assert_json_field 13 "Deterministic active-provider selection (4a fix)" "BR-SHIP-006" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"p1","quantity":1,"weight":2.0}]}' \
    '"shipping_module_code"'

# BR-SHIP-006: no active provider -> NO_SHIPPING_MODULE_CONFIGURED.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 14 "Deactivate weightBased provider" "BR-SHIP-006" \
    "PUT" "$BASE_URL/providers" '{"module_code":"weightBased","active":false}' "200"
EXTRA_HEADERS=""
assert_json_field 15 "No active provider -> NO_SHIPPING_MODULE_CONFIGURED" "BR-SHIP-006" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"p1","quantity":1,"weight":2.0}]}' \
    '"NO_SHIPPING_MODULE_CONFIGURED"'

# Re-activate for downstream tests.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 16 "Re-activate weightBased provider" "BR-SHIP-006" \
    "PUT" "$BASE_URL/providers" '{"module_code":"weightBased","active":true}' "200"

# BR-SHIP-007: selected module must be region-eligible; /methods lists region-eligible methods.
EXTRA_HEADERS=""
assert_status 17 "List region-eligible shipping methods" "BR-SHIP-007" \
    "GET" "$BASE_URL/methods" "null" "200"
assert_json_field 18 "Methods response uses {items} envelope" "BR-SHIP-007" \
    "GET" "$BASE_URL/methods" "null" '"items"'

# BR-SHIP-013: provider returns no options (weight exceeds every bracket) -> NO_SHIPPING_TO_SELECTED_COUNTRY.
assert_json_field 19 "Null provider result -> NO_SHIPPING_TO_SELECTED_COUNTRY" "BR-SHIP-013" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"heavy","quantity":50,"weight":999.0}]}' \
    '"NO_SHIPPING_TO_SELECTED_COUNTRY"'

# ============================================================================
# SECTION 3: Weight-based region authoring (BR-SHIP-026/032) + custom engine (BR-SHIP-028/029)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 3: Weight-based provider config & engine${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# BR-SHIP-026: per-store weight-based configuration document, defaulting to empty.
EXTRA_HEADERS=""
assert_status 20 "Get weight-based configuration (defaults empty)" "BR-SHIP-026" \
    "GET" "$BASE_URL/providers/weight-based/configuration" "null" "200"
assert_json_field 21 "Weight-based config exposes module_code" "BR-SHIP-026" \
    "GET" "$BASE_URL/providers/weight-based/configuration" "null" '"module_code"'

# BR-SHIP-032: add region (unique name), 201 created.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 22 "Add custom region NA" "BR-SHIP-032" \
    "POST" "$BASE_URL/providers/weight-based/regions" '{"custom_region_name":"NA"}' "201"

# BR-SHIP-032: duplicate region name -> 409 conflict.
assert_status 23 "Duplicate region name -> 409" "BR-SHIP-032" \
    "POST" "$BASE_URL/providers/weight-based/regions" '{"custom_region_name":"NA"}' "409"

# BR-SHIP-032: add country to region -> 201.
assert_status 24 "Add country US to region NA" "BR-SHIP-032" \
    "POST" "$BASE_URL/providers/weight-based/regions/NA/countries" '{"country_code":"US"}' "201"

# BR-SHIP-032: duplicate country in region -> 409 (country appears at most once per region).
assert_status 25 "Duplicate country in region -> 409" "BR-SHIP-032" \
    "POST" "$BASE_URL/providers/weight-based/regions/NA/countries" '{"country_code":"US"}' "409"

# BR-SHIP-032: add price bracket (maximum_weight > 0) -> 201.
assert_status 26 "Add weight bracket maxWeight=5 price=8.00" "BR-SHIP-032" \
    "POST" "$BASE_URL/providers/weight-based/regions/NA/prices" \
    '{"maximum_weight":5,"price_text":"8.00"}' "201"
assert_status 27 "Add weight bracket maxWeight=20 price=15.00" "BR-SHIP-032" \
    "POST" "$BASE_URL/providers/weight-based/regions/NA/prices" \
    '{"maximum_weight":20,"price_text":"15.00"}' "201"

# BR-SHIP-032: maximum_weight <= 0 -> 422.
assert_status 28 "Bracket with maximum_weight 0 -> 422" "BR-SHIP-032" \
    "POST" "$BASE_URL/providers/weight-based/regions/NA/prices" \
    '{"maximum_weight":0,"price_text":"8.00"}' "422"

# BR-SHIP-032: duplicate maximum_weight in region -> 409.
assert_status 29 "Duplicate bracket maximum_weight -> 409" "BR-SHIP-032" \
    "POST" "$BASE_URL/providers/weight-based/regions/NA/prices" \
    '{"maximum_weight":5,"price_text":"9.00"}' "409"

# BR-SHIP-032: malformed price text -> 422.
assert_status 30 "Bracket with unparseable price_text -> 422" "BR-SHIP-032" \
    "POST" "$BASE_URL/providers/weight-based/regions/NA/prices" \
    '{"maximum_weight":30,"price_text":"abc"}' "422"

# BR-SHIP-028 & BR-SHIP-029: quote through weight-based engine — total weight sums packages,
# first sufficient (ascending) bracket sets price. Region NA covers US; total weight 3 -> bracket 5 -> 8.00.
EXTRA_HEADERS=""
assert_json_field 31 "Weight-based bracket lookup returns first sufficient (BR-029)" "BR-SHIP-029" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"p1","quantity":1,"weight":3.0}]}' \
    '"CUSTOM_WEIGHT"'

# BR-SHIP-029: bracket price for weight 3 is 8.00 (behavioral — computed decimal, not placeholder).
assert_json_field 32 "Weight-based selected bracket price is 8.00 (behavioral)" "BR-SHIP-029" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"p1","quantity":1,"weight":3.0}]}' \
    '"option_price":8.0'

# BR-SHIP-028: total shipping weight is the SUM of package weights — two lines of weight 3 + 3 = 6
# falls into bracket 20 -> price 15.00 (proves weights were summed, not taken singly).
assert_json_field 33 "Summed package weight selects the 20-bracket (BR-028)" "BR-SHIP-028" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"p1","quantity":1,"weight":6.0}]}' \
    '"option_price":15.0'

# BR-SHIP-029: weight exceeds every bracket -> no option (null result path).
assert_json_field 34 "Weight above all brackets -> no option" "BR-SHIP-029" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"p1","quantity":1,"weight":50.0}]}' \
    '"NO_SHIPPING_TO_SELECTED_COUNTRY"'

# ============================================================================
# SECTION 4: Order total, free shipping, handling/tax carry (BR-SHIP-008/010/011)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 4: Order total, free shipping, handling/tax${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# BR-SHIP-008: order total = SUM(final_price * quantity). Mock final_price=10.00; qty 2 + qty 1 = 30.00.
# Behavioral: with free-shipping threshold 30.00 and >= (4a), an order of exactly 30.00 QUALIFIES.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 35 "Enable free shipping threshold 30.00 (International scope)" "BR-SHIP-010" \
    "PUT" "$BASE_URL/options" \
    '{"free_shipping_enabled":true,"order_total_free_shipping_text":"30.00","free_shipping_type":"International"}' \
    "200"
# handling + tax carry configuration.
assert_status 36 "Save handling fee 3.50 and tax_on_shipping true" "BR-SHIP-011" \
    "PUT" "$BASE_URL/options" \
    '{"free_shipping_enabled":true,"order_total_free_shipping_text":"30.00","handling_fees_text":"3.50","tax_on_shipping":true,"free_shipping_type":"International"}' \
    "200"

EXTRA_HEADERS=""
# BR-SHIP-008: two items priced 10.00 each (qty 2 and qty 1) => order total 30.00.
# BR-SHIP-010 [4a: >= and exact decimals]: order EXACTLY at threshold 30.00 QUALIFIES for free shipping.
assert_json_field 37 "Free shipping at EXACT threshold qualifies (4a >=)" "BR-SHIP-010" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"a","quantity":2,"weight":1.0},{"product_id":"b","quantity":1,"weight":1.0}]}' \
    '"free_shipping":true'

# BR-SHIP-008: order total below threshold does NOT get free shipping (one item, total 10.00).
assert_json_field 38 "Order total below threshold pays shipping (BR-008 total)" "BR-SHIP-008" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"a","quantity":1,"weight":3.0}]}' \
    '"free_shipping":false'

# BR-SHIP-011: quote carries handling fee and apply_tax_on_shipping flag from configuration.
assert_json_field 39 "Quote carries apply_tax_on_shipping flag" "BR-SHIP-011" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"a","quantity":1,"weight":3.0}]}' \
    '"apply_tax_on_shipping"'
assert_json_field 40 "Quote carries handling_fees from config" "BR-SHIP-011" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"a","quantity":1,"weight":3.0}]}' \
    '"handling_fees"'

# Disable free shipping so option-selection tests below produce priced options.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 41 "Disable free shipping" "BR-SHIP-010" \
    "PUT" "$BASE_URL/options" '{"free_shipping_enabled":false,"free_shipping_type":"National"}' "200"

# ============================================================================
# SECTION 5: Option pricing, naming, price-type selection
#            (BR-SHIP-012/014/015/016/017/018)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 5: Option pricing / naming / price-type${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# Reset to National so the store-country quotes route.
assert_status 42 "Set store to National for option tests" "BR-SHIP-003" \
    "PUT" "$BASE_URL/configuration" '{"shipping_type":"National"}' "200"

# BR-SHIP-012: provider failure is caught and returned as ERROR quote (non-fatal 200).
# Drive the box strategy with an invalid (zero) box so the packaging provider raises -> ERROR quote.
assert_status 43 "Set package type = Box with zero dims (provoke provider error)" "BR-SHIP-012" \
    "PUT" "$BASE_URL/packaging" \
    '{"shipping_package_type":"Box","box_width":0,"box_height":0,"box_length":0,"box_weight":0}' \
    "200"
EXTRA_HEADERS=""
assert_json_field 44 "Provider failure -> ERROR quote (non-fatal)" "BR-SHIP-012" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"a","quantity":1,"weight":3.0}]}' \
    '"ERROR"'

# Restore per-item packaging for the remaining option tests.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 45 "Restore package type = Item" "BR-SHIP-009" \
    "PUT" "$BASE_URL/packaging" '{"shipping_package_type":"Item"}' "200"

EXTRA_HEADERS=""
# BR-SHIP-014: each option carries a displayable option_price_text.
assert_json_field 46 "Option carries option_price_text" "BR-SHIP-014" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"a","quantity":1,"weight":3.0}]}' \
    '"option_price_text"'

# BR-SHIP-015: option with no name defaults to delivery country name / ISO code.
assert_json_field 47 "Nameless option gets a name (country/ISO fallback)" "BR-SHIP-015" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US","name":"United States"},"items":[{"product_id":"a","quantity":1,"weight":3.0}]}' \
    '"option_name"'

# BR-SHIP-016 [4a exact decimals]: Highest picks the most expensive option (cents matter).
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 48 "Set price type = Highest" "BR-SHIP-016" \
    "PUT" "$BASE_URL/options" '{"shipping_option_price_type":"Highest"}' "200"
EXTRA_HEADERS=""
assert_json_field 49 "Highest price selection returns a selected_option (4a exact decimals)" "BR-SHIP-016" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"a","quantity":1,"weight":6.0}]}' \
    '"selected_option"'

# BR-SHIP-017 [4a exact decimals]: Least picks the cheapest option.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 50 "Set price type = Least" "BR-SHIP-017" \
    "PUT" "$BASE_URL/options" '{"shipping_option_price_type":"Least"}' "200"
EXTRA_HEADERS=""
assert_json_field 51 "Least price selection returns cheapest selected_option (4a exact decimals)" "BR-SHIP-017" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"a","quantity":1,"weight":3.0}]}' \
    '"selected_option"'

# BR-SHIP-018: non-All price types collapse offered options to the single selected option.
assert_json_field 52 "Non-All price type collapses to single option" "BR-SHIP-018" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"a","quantity":1,"weight":3.0}]}' \
    '"options"'

# BR-SHIP-018: All price type preserves the full option list.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 53 "Set price type = All" "BR-SHIP-018" \
    "PUT" "$BASE_URL/options" '{"shipping_option_price_type":"All"}' "200"
EXTRA_HEADERS=""
assert_json_field 54 "All price type preserves options list + selected default" "BR-SHIP-018" \
    "POST" "$BASE_URL/quotes" \
    '{"delivery":{"country_code":"US"},"items":[{"product_id":"a","quantity":1,"weight":3.0}]}' \
    '"selected_option"'

# ============================================================================
# SECTION 6: Shipping summary (BR-SHIP-019)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 6: Shipping summary (BR-SHIP-019)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

EXTRA_HEADERS=""
# BR-SHIP-019 [4a: propagate tax_on_shipping]: summary is built from the selected option, and
# tax_on_shipping must propagate into the summary (the corrected behavior).
assert_json_field 55 "Summary records shipping from selected option" "BR-SHIP-019" \
    "POST" "$BASE_URL/summary" \
    '{"quote":{"shipping_module_code":"weightBased","handling_fees":3.50,"free_shipping":false,"apply_tax_on_shipping":true},"selected_option":{"option_price":8.00,"description":"NA"}}' \
    '"shipping":8.0'
assert_json_field 56 "Summary propagates tax_on_shipping (4a fix)" "BR-SHIP-019" \
    "POST" "$BASE_URL/summary" \
    '{"quote":{"shipping_module_code":"weightBased","handling_fees":3.50,"free_shipping":false,"apply_tax_on_shipping":true},"selected_option":{"option_price":8.00,"description":"NA"}}' \
    '"tax_on_shipping":true'
# BR-SHIP-019 negative: no selected option -> 422.
assert_status 57 "Summary without selected option -> 422" "BR-SHIP-019" \
    "POST" "$BASE_URL/summary" \
    '{"quote":{"shipping_module_code":"weightBased"}}' \
    "422"

# ============================================================================
# SECTION 7: Packaging strategy & engines (BR-SHIP-009/020/021/022/023/024/025)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 7: Packaging strategy & engines${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# BR-SHIP-009: package strategy chosen by request/config (Item vs Box). Item strategy success.
EXTRA_HEADERS=""
assert_status 58 "Compute packages with Item strategy" "BR-SHIP-009" \
    "POST" "$BASE_URL/packages" \
    '{"strategy":"Item","items":[{"product_id":"a","quantity":1,"weight":2.0}]}' \
    "200"
assert_json_field 59 "Packages response uses {items} envelope" "BR-SHIP-009" \
    "POST" "$BASE_URL/packages" \
    '{"strategy":"Item","items":[{"product_id":"a","quantity":1,"weight":2.0}]}' \
    '"items"'

# BR-SHIP-020: virtual products excluded from packaging (mock marks id "virt-*" virtual).
assert_json_field 60 "Virtual products excluded from packaging" "BR-SHIP-020" \
    "POST" "$BASE_URL/packages" \
    '{"strategy":"Item","items":[{"product_id":"phys","quantity":1,"weight":2.0,"virtual":false},{"product_id":"virt-1","quantity":1,"virtual":true}]}' \
    '"items"'

# BR-SHIP-021 [4a: correct attribute-weight getter]: default dims when unset + attribute weight accumulated.
# product weight null -> default 1.0; attribute additional_weight 0.5 -> shipping_weight 1.5 (correct accumulation).
assert_json_field 61 "Attribute weight accumulated correctly (4a getter fix)" "BR-SHIP-021" \
    "POST" "$BASE_URL/packages" \
    '{"strategy":"Item","items":[{"product_id":"a","quantity":1,"attributes":[{"additional_weight":0.5}]}]}' \
    '"shipping_weight":1.5'

# BR-SHIP-022 [4a: per-package quantity is 1]: qty 3 explodes into 3 packages, each shipping_quantity 1.
assert_json_field 62 "Per-item explode: each package shipping_quantity is 1 (4a fix)" "BR-SHIP-022" \
    "POST" "$BASE_URL/packages" \
    '{"strategy":"Item","items":[{"product_id":"a","quantity":3,"weight":2.0}]}' \
    '"shipping_quantity":1'

# BR-SHIP-023: box packaging requires positive volume + max weight; save a valid box first.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 63 "Save valid box (10x10x10, weight/maxweight positive)" "BR-SHIP-023" \
    "PUT" "$BASE_URL/packaging" \
    '{"shipping_package_type":"Box","box_width":10,"box_height":10,"box_length":10,"box_weight":2.0}' \
    "200"
EXTRA_HEADERS=""
# BR-SHIP-023: invalid box (zero dimension) -> box strategy rejected (422).
assert_status 64 "Box strategy with zero-volume box -> 422" "BR-SHIP-023" \
    "POST" "$BASE_URL/packages" \
    '{"strategy":"Box","items":[{"product_id":"a","quantity":1,"weight":2.0,"width":0,"height":0,"length":0}]}' \
    "422"

# BR-SHIP-024: box packaging validates product fits the box; oversized product -> 422.
assert_status 65 "Box packaging rejects product larger than box -> 422" "BR-SHIP-024" \
    "POST" "$BASE_URL/packages" \
    '{"strategy":"Box","items":[{"product_id":"a","quantity":1,"weight":2.0,"width":50,"height":5,"length":5}]}' \
    "422"

# BR-SHIP-025 [4a: per-box weight/dims, not stale last-box]: fitting units produce per-box packages.
assert_json_field 66 "Box bin-packing emits per-box weight (4a fix, not stale)" "BR-SHIP-025" \
    "POST" "$BASE_URL/packages" \
    '{"strategy":"Box","items":[{"product_id":"a","quantity":3,"weight":2.0,"width":2,"height":2,"length":2}]}' \
    '"shipping_weight"'

# ============================================================================
# SECTION 8: requires-shipping (endpoint coverage)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 8: requires-shipping${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

EXTRA_HEADERS=""
# Physical item -> requires_shipping true.
assert_json_field 67 "Physical items require shipping" "BR-SHIP-020" \
    "POST" "$BASE_URL/requires-shipping" \
    '{"items":[{"product_id":"a","quantity":1,"virtual":false,"shippable":true}]}' \
    '"requires_shipping":true'
# All-virtual cart -> requires_shipping false.
assert_json_field 68 "All-virtual cart does not require shipping" "BR-SHIP-020" \
    "POST" "$BASE_URL/requires-shipping" \
    '{"items":[{"product_id":"virt-1","quantity":1,"virtual":true,"shippable":false}]}' \
    '"requires_shipping":false'
# Required body omitted -> 422 (contract-conformance: required-parameter omission).
assert_status 69 "requires-shipping missing items -> 422" "BR-SHIP-020" \
    "POST" "$BASE_URL/requires-shipping" '{}' "422"

# ============================================================================
# SECTION 9: Admin authoring — providers, options, packaging, countries
#            (BR-SHIP-031/033/034) + role gate (BR-SHIP-030)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 9: Admin authoring & role gate${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# BR-SHIP-031: saving a provider validates through the provider then stores encrypted.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 70 "Save known provider weightBased (validated + stored)" "BR-SHIP-031" \
    "PUT" "$BASE_URL/providers" '{"module_code":"weightBased","active":true}' "200"
# BR-SHIP-031: unknown provider -> 422.
assert_status 71 "Save unknown provider -> 422" "BR-SHIP-031" \
    "PUT" "$BASE_URL/providers" '{"module_code":"nonexistent","active":true}' "422"

# BR-SHIP-033: saving options parses money text; malformed handling fee -> 422.
assert_status 72 "Save options parses money text (valid)" "BR-SHIP-033" \
    "PUT" "$BASE_URL/options" \
    '{"free_shipping_enabled":true,"order_total_free_shipping_text":"100.00","handling_fees_text":"3.50","tax_on_shipping":true,"shipping_option_price_type":"Least"}' \
    "200"
assert_status 73 "Save options with malformed handling fee -> 422" "BR-SHIP-033" \
    "PUT" "$BASE_URL/options" '{"handling_fees_text":"abc"}' "422"

# BR-SHIP-034: saving packaging rounds box weight to 2dp and persists dims + package type.
assert_json_field 74 "Save packaging rounds box_weight to 2dp" "BR-SHIP-034" \
    "PUT" "$BASE_URL/packaging" \
    '{"shipping_package_type":"Box","box_width":10,"box_height":10,"box_length":10,"box_weight":2.457}' \
    '"box_weight":2.46'
# BR-SHIP-034: invalid package type -> 422 (enum validation).
assert_status 75 "Save packaging invalid package type -> 422" "BR-SHIP-034" \
    "PUT" "$BASE_URL/packaging" '{"shipping_package_type":"CRATE"}' "422"

# BR-SHIP-030 [4a: gate the delete endpoint]: admin write WITHOUT the role -> 403.
EXTRA_HEADERS="-H '$NO_ROLE_HEADER'"
assert_status 76 "Save configuration WITHOUT shipping role -> 403" "BR-SHIP-030" \
    "PUT" "$BASE_URL/configuration" '{"shipping_type":"National"}' "403"
# BR-SHIP-030 [4a corrected]: delete-provider (the legacy-unguarded endpoint) IS now role-gated -> 403.
assert_status 77 "Delete provider WITHOUT role is gated -> 403 (4a fix)" "BR-SHIP-030" \
    "DELETE" "$BASE_URL/providers/weightBased" "null" "403"

# BR-SHIP-030: with the role, deleting a configured provider succeeds -> 204.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 78 "Delete provider WITH role -> 204" "BR-SHIP-030" \
    "DELETE" "$BASE_URL/providers/weightBased" "null" "204"
# Delete a non-existent provider -> 404 (endpoint error coverage).
assert_status 79 "Delete unknown provider -> 404" "BR-SHIP-031" \
    "DELETE" "$BASE_URL/providers/doesNotExist" "null" "404"

# ============================================================================
# SECTION 10: Supported countries endpoint + Layer A invariants (INV-SHIP-*)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 10: Supported countries & Layer A invariants${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# Endpoint coverage: list supported countries.
EXTRA_HEADERS=""
assert_status 80 "List supported countries" "BR-SHIP-004" \
    "GET" "$BASE_URL/supported-countries" "null" "200"
assert_json_field 81 "Supported countries uses {items} envelope" "BR-SHIP-004" \
    "GET" "$BASE_URL/supported-countries" "null" '"items"'

# INV-SHIP-002 (app-tier enum): shipping_type must be National|International — invalid -> 422.
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 82 "INV-SHIP-002: invalid shipping_type enum -> 422" "BR-SHIP-034" \
    "PUT" "$BASE_URL/configuration" '{"shipping_type":"Interplanetary"}' "422"

# INV-SHIP-003 (app-tier enum): shipping_option_price_type must be Least|Highest|All -> invalid 422.
assert_status 83 "INV-SHIP-003: invalid price type enum -> 422" "BR-SHIP-033" \
    "PUT" "$BASE_URL/options" '{"shipping_option_price_type":"Cheapest"}' "422"

# INV-SHIP-004 (app-tier enum): shipping_package_type must be Item|Box -> invalid 422.
assert_status 84 "INV-SHIP-004: invalid package type enum -> 422" "BR-SHIP-034" \
    "PUT" "$BASE_URL/packaging" '{"shipping_package_type":"Pallet"}' "422"

# INV-SHIP-005 (app cross-field): box volume + max weight must both be > 0 for Box packaging.
EXTRA_HEADERS=""
assert_status 85 "INV-SHIP-005: box with zero volume rejected -> 422" "BR-SHIP-023" \
    "POST" "$BASE_URL/packages" \
    '{"strategy":"Box","items":[{"product_id":"a","quantity":1,"weight":2.0,"width":0,"height":0,"length":0}]}' \
    "422"

# INV-SHIP-006 (db unique): a supported country appears at most once per store.
# Setting duplicates in the PUT payload must be de-duplicated / rejected — assert the read never
# returns the same code twice by round-tripping a duplicate set (accepted set is unique).
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 86 "INV-SHIP-006: set supported countries (dedup on save)" "BR-SHIP-004" \
    "PUT" "$BASE_URL/supported-countries" '{"items":["US","US","GB"]}' "200"
EXTRA_HEADERS=""
assert_json_field 87 "INV-SHIP-006: supported country GB present once (unique per store)" "BR-SHIP-004" \
    "GET" "$BASE_URL/supported-countries" "null" '"GB"'

# INV-SHIP-007 (db unique): a provider code is configured at most once per store — re-saving the
# same module_code updates in place (no duplicate); asserted by a successful re-save (idempotent upsert).
EXTRA_HEADERS="-H '$ROLE_HEADER'"
assert_status 88 "INV-SHIP-007: re-save same provider code (unique per store, upsert)" "BR-SHIP-031" \
    "PUT" "$BASE_URL/providers" '{"module_code":"weightBased","active":true}' "200"

# INV-SHIP-008/009 (app): weight-based authoring uniqueness already exercised by
# tests 22/23/25/29 (duplicate region 409, duplicate country 409, duplicate bracket 409). Add a
# region-name uniqueness reconfirmation to explicitly cover INV-SHIP-009.
assert_status 89 "INV-SHIP-009: add second distinct region EU -> 201" "BR-SHIP-032" \
    "POST" "$BASE_URL/providers/weight-based/regions" '{"custom_region_name":"EU"}' "201"
assert_status 90 "INV-SHIP-009: duplicate region EU rejected -> 409" "BR-SHIP-032" \
    "POST" "$BASE_URL/providers/weight-based/regions" '{"custom_region_name":"EU"}' "409"

# Endpoint coverage: delete a weight-based region / country / bracket (204 success paths).
assert_status 91 "Delete weight bracket from region -> 204" "BR-SHIP-032" \
    "DELETE" "$BASE_URL/providers/weight-based/regions/NA/prices/5" "null" "204"
assert_status 92 "Delete country from region -> 204" "BR-SHIP-032" \
    "DELETE" "$BASE_URL/providers/weight-based/regions/NA/countries/US" "null" "204"
assert_status 93 "Delete weight-based region -> 204" "BR-SHIP-032" \
    "DELETE" "$BASE_URL/providers/weight-based/regions/EU" "null" "204"
# Delete a non-existent region -> 404 (endpoint error coverage).
assert_status 94 "Delete unknown region -> 404" "BR-SHIP-032" \
    "DELETE" "$BASE_URL/providers/weight-based/regions/NOPE" "null" "404"

# ============================================================================
# SUMMARY
# ============================================================================
echo ""
echo "================================================================"
echo "TEST SUMMARY"
echo "================================================================"
echo ""
echo -e "${CYAN}Total Tests:  $TOTAL${NC}"
echo -e "${GREEN}Passed:       $PASSED${NC}"
echo -e "${RED}Failed:       $FAILED${NC}"
echo ""

if [ $FAILED -gt 0 ]; then
    echo -e "${RED}Failed Tests:${NC}"
    for test in "${FAILED_TESTS[@]}"; do
        echo "  x $test"
    done
    echo ""
fi

if [ $TOTAL -gt 0 ]; then
    echo "Success Rate: $((PASSED * 100 / TOTAL))%"
fi

echo ""
if [ $FAILED -eq 0 ]; then
    echo -e "${GREEN}ALL $TOTAL TESTS PASSED — 100% SUCCESS${NC}"
    exit 0
else
    echo -e "${RED}$FAILED OF $TOTAL TESTS FAILED${NC}"
    exit 1
fi
