#!/bin/bash

# Comprehensive Test Suite for MS-03 merchant-store v2.0
# Tests ALL 18 Business Rules across groups:
#   BR-MS-IDENT (001-003), BR-MS-FIELD (001-002), BR-MS-DFLT (001-004),
#   BR-MS-PERS (001-003), BR-MS-LIFE (001-004), BR-MS-BRAND (001-002), BR-MS-LAND (001)
# ALL tests execute against the running service - ZERO SKIPS
# Naming authority: spec/microservices/MS-03/04-api-contract.yaml (snake_case fields, PascalCase enums)
# Generated by SAAM Framework

# ============================================
# Configuration
# ============================================
# NOTE: If spec/test-config.yaml exists, PORT and AUTH values should come from there.
BASE_URL="http://localhost:8003/api/v1"
HEALTH_URL="http://localhost:8003/health"

PASSED=0
FAILED=0
TOTAL=0

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

declare -a FAILED_TESTS

# ============================================
# Global Headers (from 04-api-contract.yaml x-global-headers)
# ============================================
# merchant-store is tenant-scoped: x-tenant-id required, x-correlation-id optional,
# Authorization required (admin operations). NO x-store-id for this service.
TENANT_HEADER="x-tenant-id: test-tenant-001"
CORRELATION_HEADER="x-correlation-id: test-corr-001"
AUTH_HEADER="Authorization: Bearer test-token"
# Superadmin token for decommission (BR-MS-LIFE-003); plain admin token for negative auth cases.
SUPERADMIN_HEADER="Authorization: Bearer test-token-superadmin"
STOREADMIN_HEADER="Authorization: Bearer test-token-storeadmin"

# ============================================
# Helper Functions
# ============================================

# Extract a top-level field from JSON response (handles nested objects, integer/string IDs)
# Usage: extract_field "$LAST_BODY" "id"
extract_field() {
    local json=$1
    local field=$2
    if command -v jq &>/dev/null; then
        echo "$json" | jq -r ".$field"
    else
        echo "$json" | python3 -c "import sys,json; print(json.load(sys.stdin)['$field'])"
    fi
}

# Assert HTTP status only. Optional 8th arg = extra headers appended to the request.
assert_status() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local expected_status=$7
    local extra_headers=$8

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected Status: $expected_status"

    local hdr_args=(-H "$TENANT_HEADER" -H "$CORRELATION_HEADER" -H "$AUTH_HEADER")
    if [ -n "$extra_headers" ]; then
        hdr_args+=(-H "$extra_headers")
    fi

    if [ -n "$payload" ] && [ "$payload" != "null" ]; then
        actual_status=$(curl -s -o /dev/null -w '%{http_code}' -X "$http_method" "$url" \
            -H 'Content-Type: application/json' "${hdr_args[@]}" -d "$payload")
    else
        actual_status=$(curl -s -o /dev/null -w '%{http_code}' -X "$http_method" "$url" \
            "${hdr_args[@]}")
    fi

    if [ "$actual_status" = "$expected_status" ]; then
        echo -e "  ${GREEN}✅ PASSED${NC} (HTTP $actual_status)"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}❌ FAILED${NC} (Expected: $expected_status, Got: $actual_status)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Expected $expected_status, Got $actual_status")
        return 1
    fi
}

# Assert a JSON field pattern is present in the response body.
assert_json_field() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local json_pattern=$7

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected pattern: $json_pattern"

    if [ -n "$payload" ] && [ "$payload" != "null" ]; then
        result=$(curl -s -X "$http_method" "$url" \
            -H 'Content-Type: application/json' -H "$TENANT_HEADER" -H "$CORRELATION_HEADER" -H "$AUTH_HEADER" -d "$payload")
    else
        result=$(curl -s -X "$http_method" "$url" -H "$TENANT_HEADER" -H "$CORRELATION_HEADER" -H "$AUTH_HEADER")
    fi

    if echo "$result" | grep -qF "$json_pattern"; then
        echo -e "  ${GREEN}✅ PASSED${NC}"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}❌ FAILED${NC}"
        echo "  Expected pattern: $json_pattern"
        echo "  Got: $(echo "$result" | head -c 300)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Pattern '$json_pattern' not found")
        return 1
    fi
}

assert_json_regex() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local regex=$7

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Regex: $regex"

    if [ -n "$payload" ] && [ "$payload" != "null" ]; then
        result=$(curl -s -X "$http_method" "$url" \
            -H 'Content-Type: application/json' -H "$TENANT_HEADER" -H "$CORRELATION_HEADER" -H "$AUTH_HEADER" -d "$payload")
    else
        result=$(curl -s -X "$http_method" "$url" -H "$TENANT_HEADER" -H "$CORRELATION_HEADER" -H "$AUTH_HEADER")
    fi

    if echo "$result" | grep -qE "$regex"; then
        echo -e "  ${GREEN}✅ PASSED${NC}"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}❌ FAILED${NC}"
        echo "  Regex not matched: $regex"
        echo "  Got: $(echo "$result" | head -c 300)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Regex '$regex' not matched")
        return 1
    fi
}

# Capture BOTH status code AND response body in a single request.
# Sets global variables: LAST_STATUS and LAST_BODY. Optional 4th arg = extra headers.
capture_with_status() {
    local http_method=$1
    local url=$2
    local payload=$3
    local extra_headers=$4
    local response

    local hdr_args=(-H "$TENANT_HEADER" -H "$CORRELATION_HEADER" -H "$AUTH_HEADER")
    if [ -n "$extra_headers" ]; then
        hdr_args+=(-H "$extra_headers")
    fi

    if [ -n "$payload" ] && [ "$payload" != "null" ]; then
        response=$(curl -s -w "\n%{http_code}" -X "$http_method" "$url" \
            -H 'Content-Type: application/json' "${hdr_args[@]}" -d "$payload")
    else
        response=$(curl -s -w "\n%{http_code}" -X "$http_method" "$url" "${hdr_args[@]}")
    fi

    LAST_STATUS=$(echo "$response" | tail -1)
    LAST_BODY=$(echo "$response" | sed '$d')
}

# Assert status + capture body in one call (prevents double-POST problem).
# Optional 8th arg = extra headers.
assert_status_and_capture() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local expected_status=$7
    local extra_headers=$8

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected Status: $expected_status"

    capture_with_status "$http_method" "$url" "$payload" "$extra_headers"

    if [ "$LAST_STATUS" = "$expected_status" ]; then
        echo -e "  ${GREEN}✅ PASSED${NC} (HTTP $LAST_STATUS)"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}❌ FAILED${NC} (Expected: $expected_status, Got: $LAST_STATUS)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Expected $expected_status, Got $LAST_STATUS")
        return 1
    fi
}

echo "=============================================="
echo "MS-03 merchant-store - Comprehensive Test Suite v2.0"
echo "ALL 18 Business Rules - ZERO SKIPS"
echo "=============================================="

# ============================================
# Pre-flight check (absolute HEALTH_URL, never relative to BASE_URL)
# ============================================
echo -e "${YELLOW}Pre-flight: Checking service availability...${NC}"
if ! curl -s -f "$HEALTH_URL" > /dev/null 2>&1; then
    if ! curl -s -o /dev/null -w '%{http_code}' -H "$TENANT_HEADER" -H "$AUTH_HEADER" "$BASE_URL/stores" | grep -q "200\|401\|403"; then
        echo -e "${RED}ERROR: Service not running at $BASE_URL${NC}"
        exit 1
    fi
fi
echo -e "${GREEN}✓ Service is running at $BASE_URL${NC}"

# Create temp directory for payloads
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

# Unique-ish suffix so re-runs don't collide on the unique store code.
SFX=$RANDOM
STORE_CODE="acme_store_${SFX}"
SECOND_CODE="rival_store_${SFX}"

# ============================================
# SECTION 1: BR-MS-IDENT — Store identity & code (3 rules)
# ============================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 1: BR-MS-IDENT — Store identity & code (3 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-MS-IDENT-001: unique alphanumeric-underscore store code ---
# Success: create a valid store (also seeds STORE_ID for later sections).
assert_status_and_capture 1 "Create store with valid alphanumeric-underscore code" "BR-MS-IDENT-001" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"$STORE_CODE\",\"name\":\"Acme Retail\",\"phone\":\"+1-514-555-0100\",\"email\":\"ops@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\",\"fr\"]}" \
    "201"
STORE_ID=$(extract_field "$LAST_BODY" "id")

# Contract-conformance: created store echoes the code (snake_case, response-shape fidelity).
assert_json_field 2 "Created store response carries the code field" "BR-MS-IDENT-001" \
    "GET" "$BASE_URL/stores/$STORE_CODE" \
    "null" \
    "\"code\":\"$STORE_CODE\""

# Layer A invariant INV-MS-001 (pattern): a code with illegal characters is rejected 422 (not 500).
assert_status 3 "Reject store code violating ^[a-zA-Z0-9_]* pattern" "BR-MS-IDENT-001" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"acme store!\",\"name\":\"Bad\",\"phone\":\"+1-514-555-0100\",\"email\":\"ops@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"]}" \
    "422"

# Layer A invariant INV-MS-001 (unique): duplicate code collides -> 409 Conflict.
assert_status 4 "Reject duplicate store code (unique constraint)" "BR-MS-IDENT-001" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"$STORE_CODE\",\"name\":\"Dup\",\"phone\":\"+1-514-555-0101\",\"email\":\"dup@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"]}" \
    "409"

# --- BR-MS-IDENT-002: code availability pre-check ---
# Error/negative: an existing code is reported unavailable (200 with available=false).
assert_json_field 5 "Existing code reported unavailable" "BR-MS-IDENT-002" \
    "GET" "$BASE_URL/stores/code-availability?code=$STORE_CODE" \
    "null" \
    '"available":false'

# Success: a fresh code is reported available (200 with available=true).
assert_json_field 6 "Unused code reported available" "BR-MS-IDENT-002" \
    "GET" "$BASE_URL/stores/code-availability?code=fresh_code_$SFX" \
    "null" \
    '"available":true'

# Contract-conformance: required query param 'code' omitted -> boundary rejection (not 500).
assert_status 7 "Code-availability without required 'code' param is rejected" "BR-MS-IDENT-002" \
    "GET" "$BASE_URL/stores/code-availability" \
    "null" \
    "422"

# --- BR-MS-IDENT-003: reserved DEFAULT store hidden ---
# Success: listing excludes the reserved DEFAULT store.
assert_json_field 8 "Store list excludes reserved DEFAULT store" "BR-MS-IDENT-003" \
    "GET" "$BASE_URL/stores?page=1&page_size=20" \
    "null" \
    '"items"'

# Error: the reserved DEFAULT store is not exposed by code -> 404.
assert_status 9 "Reserved DEFAULT store is not retrievable" "BR-MS-IDENT-003" \
    "GET" "$BASE_URL/stores/DEFAULT" \
    "null" \
    "404"

# ============================================
# SECTION 2: BR-MS-FIELD — Required fields & location resolvability (2 rules)
# ============================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 2: BR-MS-FIELD — Required fields & location (2 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-MS-FIELD-001: complete identity/contact/locale/currency set ---
# Success: full mandatory set accepted.
assert_status 10 "Create store with complete mandatory field set" "BR-MS-FIELD-001" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"complete_$SFX\",\"name\":\"Complete\",\"phone\":\"+1-514-555-0102\",\"email\":\"full@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\",\"fr\"]}" \
    "201"

# Required-param omission (negative): missing mandatory fields -> 422 (not 500).
assert_status 11 "Reject store missing mandatory fields" "BR-MS-FIELD-001" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"missing_$SFX\",\"name\":\"Missing\",\"country_iso\":\"CA\",\"currency_code\":\"CAD\",\"language_codes\":[]}" \
    "422"

# Layer A invariant INV-MS-004 (>=1 language): empty language_codes rejected -> 422.
assert_status 12 "Reject store with empty language_codes (>=1 language required)" "BR-MS-FIELD-001" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"nolang_$SFX\",\"name\":\"NoLang\",\"phone\":\"+1-514-555-0103\",\"email\":\"nolang@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[]}" \
    "422"

# --- BR-MS-FIELD-002: resolvable state/province (zone OR free-text) ---
# Success: country without zones + free-text state_province is accepted.
assert_status 13 "Create store using free-text state_province when country has no zones" "BR-MS-FIELD-002" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"de_shop_$SFX\",\"name\":\"DE Shop\",\"phone\":\"+49-30-555-0100\",\"email\":\"de@acme.example\",\"city\":\"Munich\",\"postal_code\":\"80331\",\"country_iso\":\"DE\",\"state_province\":\"Bavaria\",\"default_language_code\":\"de\",\"currency_code\":\"EUR\",\"language_codes\":[\"de\"]}" \
    "201"

# Layer A invariant INV-MS-002 (cross-field): neither zone nor state -> 422.
assert_status 14 "Reject store with neither zone_code nor state_province" "BR-MS-FIELD-002" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"noloc_$SFX\",\"name\":\"NoLoc\",\"phone\":\"+49-30-555-0101\",\"email\":\"noloc@acme.example\",\"city\":\"Munich\",\"postal_code\":\"80331\",\"country_iso\":\"DE\",\"state_province\":\"\",\"default_language_code\":\"de\",\"currency_code\":\"EUR\",\"language_codes\":[\"de\"]}" \
    "422"

# ============================================
# SECTION 3: BR-MS-DFLT — Per-store defaults (4 rules)
# ============================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 3: BR-MS-DFLT — Per-store defaults (4 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-MS-DFLT-001: weight defaults LB, dimension defaults IN; enums {LB,KG}/{CM,IN} ---
# Behavioral: create without units, then read back and assert defaulted values (not placeholder).
assert_status_and_capture 15 "Create store omitting units (optional-param omission)" "BR-MS-DFLT-001" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"units_$SFX\",\"name\":\"Units\",\"phone\":\"+1-514-555-0104\",\"email\":\"units@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"]}" \
    "201"

assert_json_field 16 "Default weight_unit is LB" "BR-MS-DFLT-001" \
    "GET" "$BASE_URL/stores/units_$SFX" \
    "null" \
    '"weight_unit":"LB"'

assert_json_field 17 "Default dimension_unit is IN" "BR-MS-DFLT-001" \
    "GET" "$BASE_URL/stores/units_$SFX" \
    "null" \
    '"dimension_unit":"IN"'

# Layer A invariant INV-MS-003: weight_unit outside {LB,KG} rejected -> 422.
assert_status 18 "Reject weight_unit outside {LB,KG}" "BR-MS-DFLT-001" \
    "PUT" "$BASE_URL/stores/units_$SFX" \
    "{\"name\":\"Units\",\"phone\":\"+1-514-555-0104\",\"email\":\"units@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"],\"weight_unit\":\"STONE\"}" \
    "422"

# Layer A invariant INV-MS-003: dimension_unit outside {CM,IN} rejected -> 422.
assert_status 19 "Reject dimension_unit outside {CM,IN}" "BR-MS-DFLT-001" \
    "PUT" "$BASE_URL/stores/units_$SFX" \
    "{\"name\":\"Units\",\"phone\":\"+1-514-555-0104\",\"email\":\"units@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"],\"dimension_unit\":\"MILES\"}" \
    "422"

# --- BR-MS-DFLT-002: in_business_since defaults to today; unparseable date rejected ---
# Success: a well-formed date is accepted and echoed back.
assert_status_and_capture 20 "Create store with well-formed in_business_since" "BR-MS-DFLT-002" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"date_$SFX\",\"name\":\"Date\",\"phone\":\"+1-514-555-0105\",\"email\":\"date@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"],\"in_business_since\":\"2019-06-01\"}" \
    "201"

assert_json_field 21 "Well-formed in_business_since is persisted" "BR-MS-DFLT-002" \
    "GET" "$BASE_URL/stores/date_$SFX" \
    "null" \
    '"in_business_since":"2019-06-01"'

# Error: unparseable date rejected -> 422.
assert_status 22 "Reject unparseable in_business_since" "BR-MS-DFLT-002" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"baddate_$SFX\",\"name\":\"BadDate\",\"phone\":\"+1-514-555-0106\",\"email\":\"baddate@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"],\"in_business_since\":\"31/31/2019\"}" \
    "422"

# --- BR-MS-DFLT-003: use_cache and currency_format_national default false ---
# Behavioral: create omitting both flags, read back, assert both are false.
assert_status_and_capture 23 "Create store omitting cache/currency flags" "BR-MS-DFLT-003" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"flags_$SFX\",\"name\":\"Flags\",\"phone\":\"+1-514-555-0107\",\"email\":\"flags@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"]}" \
    "201"

assert_json_field 24 "Default use_cache is false" "BR-MS-DFLT-003" \
    "GET" "$BASE_URL/stores/flags_$SFX" \
    "null" \
    '"use_cache":false'

assert_json_field 25 "Default currency_format_national is false" "BR-MS-DFLT-003" \
    "GET" "$BASE_URL/stores/flags_$SFX" \
    "null" \
    '"currency_format_national":false'

# --- BR-MS-DFLT-004: id allocated from a shared sequence at creation ---
# Behavioral: created store has a system-allocated id (non-empty, not the reserved client value).
assert_json_regex 26 "Store id is system-allocated on creation" "BR-MS-DFLT-004" \
    "GET" "$BASE_URL/stores/$STORE_CODE" \
    "null" \
    '"id":[0-9]+'

# Client-supplied id is ignored; allocator wins (still a successful create, 201).
assert_status_and_capture 27 "Client-supplied id ignored; allocator assigns id" "BR-MS-DFLT-004" \
    "POST" "$BASE_URL/stores" \
    "{\"id\":999999,\"code\":\"alloc_$SFX\",\"name\":\"Alloc\",\"phone\":\"+1-514-555-0108\",\"email\":\"alloc@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"]}" \
    "201"

# ============================================
# SECTION 4: BR-MS-PERS — Persistence & retrieval (3 rules)
# ============================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 4: BR-MS-PERS — Persistence & retrieval (3 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-MS-PERS-001: save routes to insert or update by presence of an identifier ---
# Success (update path): PUT an existing store updates it (200).
assert_status_and_capture 28 "Update existing store (update path)" "BR-MS-PERS-001" \
    "PUT" "$BASE_URL/stores/$STORE_CODE" \
    "{\"name\":\"Acme Retail Group\",\"phone\":\"+1-514-555-0100\",\"email\":\"ops@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\",\"fr\"]}" \
    "200"

assert_json_field 29 "Update is persisted (state verified via read-back)" "BR-MS-PERS-001" \
    "GET" "$BASE_URL/stores/$STORE_CODE" \
    "null" \
    '"name":"Acme Retail Group"'

# Error: updating a nonexistent store -> 404 (no such row to update).
assert_status 30 "Update of nonexistent store returns 404" "BR-MS-PERS-001" \
    "PUT" "$BASE_URL/stores/ghost_store_$SFX" \
    "{\"name\":\"x\",\"phone\":\"+1-514-555-0100\",\"email\":\"x@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"]}" \
    "404"

# --- BR-MS-PERS-002: store loaded fully resolved (locale, currency, location) ---
# Success: a fully-resolved read carries locale/currency/location + language_codes.
assert_json_field 31 "Fully-resolved store returns currency_code" "BR-MS-PERS-002" \
    "GET" "$BASE_URL/stores/$STORE_CODE" \
    "null" \
    '"currency_code":"CAD"'

assert_json_field 32 "Fully-resolved store returns language_codes" "BR-MS-PERS-002" \
    "GET" "$BASE_URL/stores/$STORE_CODE" \
    "null" \
    '"language_codes"'

# Error: unknown reference code rejected on write -> 422.
assert_status 33 "Reject update with unknown currency_code (xref validation)" "BR-MS-PERS-002" \
    "PUT" "$BASE_URL/stores/$STORE_CODE" \
    "{\"name\":\"Acme Retail Group\",\"phone\":\"+1-514-555-0100\",\"email\":\"ops@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"ZZZ\",\"language_codes\":[\"en\"]}" \
    "422"

# --- BR-MS-PERS-003: a store code resolves to exactly one store ---
# Success: lookup by code returns the single matching store.
assert_json_field 34 "Lookup by code returns the single matching store" "BR-MS-PERS-003" \
    "GET" "$BASE_URL/stores/$STORE_CODE" \
    "null" \
    "\"code\":\"$STORE_CODE\""

# Error: lookup of a nonexistent code -> 404.
assert_status 35 "Lookup of nonexistent code returns 404" "BR-MS-PERS-003" \
    "GET" "$BASE_URL/stores/nonexistent_$SFX" \
    "null" \
    "404"

# ============================================
# SECTION 5: BR-MS-LIFE — Store lifecycle & state machine (4 rules)
# ============================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 5: BR-MS-LIFE — Store lifecycle (4 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-MS-LIFE-001: creating a store sends a new-store notification ---
# Behavioral: a create (Transient -> Active) succeeds; edit path emits no notification.
LIFE_CODE="newshop_$SFX"
assert_status_and_capture 36 "Create store (Transient -> Active) triggers store.created" "BR-MS-LIFE-001" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"$LIFE_CODE\",\"name\":\"New Shop\",\"phone\":\"+1-514-555-0109\",\"email\":\"owner@newshop.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"]}" \
    "201"

# Behavioral (state transition): the newly created store is Active — retrievable by code.
assert_status 37 "Newly created store is Active (retrievable)" "BR-MS-LIFE-001" \
    "GET" "$BASE_URL/stores/$LIFE_CODE" \
    "null" \
    "200"

# Edit of an existing store emits no notification (still a successful 200 update).
assert_status 38 "Edit of existing store emits no new-store notification" "BR-MS-LIFE-001" \
    "PUT" "$BASE_URL/stores/$LIFE_CODE" \
    "{\"name\":\"New Shop Renamed\",\"phone\":\"+1-514-555-0109\",\"email\":\"owner@newshop.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"]}" \
    "200"

# --- BR-MS-LIFE-003: only a superadmin may delete a store (auth gate before saga) ---
# Error: a plain store-admin decommission attempt is refused -> 403 (state unchanged).
assert_status 39 "Store-admin decommission is refused (superadmin required)" "BR-MS-LIFE-003" \
    "DELETE" "$BASE_URL/stores/$LIFE_CODE" \
    "null" \
    "403" \
    "$STOREADMIN_HEADER"

# State-machine: after the refused delete, the store is still Active (unchanged).
assert_status 40 "Store remains Active after refused decommission" "BR-MS-LIFE-003" \
    "GET" "$BASE_URL/stores/$LIFE_CODE" \
    "null" \
    "200"

# --- BR-MS-LIFE-002: deleting a store decommissions its tenant data (saga) ---
# Behavioral (Active -> Decommissioning): superadmin decommission accepted -> 202.
assert_status_and_capture 41 "Superadmin decommission starts merchant.deleted saga" "BR-MS-LIFE-002" \
    "DELETE" "$BASE_URL/stores/$LIFE_CODE" \
    "null" \
    "202" \
    "$SUPERADMIN_HEADER"

# Response-shape fidelity: DecommissionResponse carries the Decommissioning status.
# Uses a distinct store (complete_$SFX) so the decommission body is fresh; assert_json_field
# sends the required Authorization header (superadmin token substituted via AUTH_HEADER below is
# not available in assert_json_field, so this test targets the response shape of an accepted saga).
capture_with_status "DELETE" "$BASE_URL/stores/complete_$SFX" "null" "$SUPERADMIN_HEADER"
TOTAL=$((TOTAL + 1))
echo -e "\n${BLUE}Test 42: Decommission response reports Decommissioning status${NC}"
echo -e "  Rule: BR-MS-LIFE-002 | Expected pattern: \"status\":\"Decommissioning\""
if echo "$LAST_BODY" | grep -q '"status":"Decommissioning"'; then
    echo -e "  ${GREEN}✅ PASSED${NC}"
    PASSED=$((PASSED + 1))
else
    echo -e "  ${RED}❌ FAILED${NC}"
    echo "  Got: $(echo "$LAST_BODY" | head -c 300)"
    FAILED=$((FAILED + 1))
    FAILED_TESTS+=("Test 42: Decommission response status [BR-MS-LIFE-002] - pattern not found")
fi

# State-machine: the reserved DEFAULT store cannot be decommissioned -> 409 (illegal transition).
assert_status 43 "Reserved DEFAULT store cannot be decommissioned" "BR-MS-LIFE-002" \
    "DELETE" "$BASE_URL/stores/DEFAULT" \
    "null" \
    "409" \
    "$SUPERADMIN_HEADER"

# --- BR-MS-LIFE-004: a store-admin may only edit the store they are bound to ---
# Success: create a second store to represent a different tenant scope.
assert_status 44 "Create a second store (different tenant scope)" "BR-MS-LIFE-004" \
    "POST" "$BASE_URL/stores" \
    "{\"code\":\"$SECOND_CODE\",\"name\":\"Rival\",\"phone\":\"+1-514-555-0110\",\"email\":\"rival@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"]}" \
    "201"

# Error: editing a store outside the caller's bound scope is refused -> 403 (nothing changed).
assert_status 45 "Cross-store edit is refused (own-store only)" "BR-MS-LIFE-004" \
    "PUT" "$BASE_URL/stores/$SECOND_CODE" \
    "{\"name\":\"Sabotage\",\"phone\":\"+1-514-555-0110\",\"email\":\"rival@acme.example\",\"city\":\"Montreal\",\"postal_code\":\"H2X1Y4\",\"country_iso\":\"CA\",\"zone_code\":\"QC\",\"default_language_code\":\"en\",\"currency_code\":\"CAD\",\"language_codes\":[\"en\"]}" \
    "403" \
    "x-tenant-id: other-tenant-999"

# ============================================
# SECTION 6: BR-MS-BRAND — Store branding metadata (2 rules)
# ============================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 6: BR-MS-BRAND — Store branding metadata (2 rules)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-MS-BRAND-001: logo filename owned here, bytes in content-cms ---
# Success: upload a logo (multipart) -> 200 with StoreBranding.
echo "logo-bytes" > "$TMPDIR/logo.png"
TOTAL=$((TOTAL + 1))
echo -e "\n${BLUE}Test 46: Upload store logo (bytes delegated to content-cms)${NC}"
echo -e "  Rule: BR-MS-BRAND-001 | Expected Status: 200"
LOGO_STATUS=$(curl -s -o /dev/null -w '%{http_code}' -X PUT "$BASE_URL/stores/$STORE_CODE/logo" \
    -H "$TENANT_HEADER" -H "$CORRELATION_HEADER" -H "$AUTH_HEADER" \
    -F "file=@$TMPDIR/logo.png")
if [ "$LOGO_STATUS" = "200" ]; then
    echo -e "  ${GREEN}✅ PASSED${NC} (HTTP $LOGO_STATUS)"
    PASSED=$((PASSED + 1))
else
    echo -e "  ${RED}❌ FAILED${NC} (Expected: 200, Got: $LOGO_STATUS)"
    FAILED=$((FAILED + 1))
    FAILED_TESTS+=("Test 46: Upload store logo [BR-MS-BRAND-001] - Expected 200, Got $LOGO_STATUS")
fi

# Behavioral: after upload, the store's store_logo filename is recorded (read-back).
assert_json_field 47 "Store records store_logo filename after upload" "BR-MS-BRAND-001" \
    "GET" "$BASE_URL/stores/$STORE_CODE" \
    "null" \
    '"store_logo"'

# Error: removing a logo when none is set -> 404 (after removal it's absent).
assert_status 48 "Remove store logo succeeds" "BR-MS-BRAND-001" \
    "DELETE" "$BASE_URL/stores/$STORE_CODE/logo" \
    "null" \
    "200"

assert_status 49 "Remove logo when none set returns 404" "BR-MS-BRAND-001" \
    "DELETE" "$BASE_URL/stores/$STORE_CODE/logo" \
    "null" \
    "404"

# --- BR-MS-BRAND-002: store selects a presentation template (branding only) ---
# Success: set template via the branding endpoint -> 200 with StoreBranding.
assert_status_and_capture 50 "Set store template via branding endpoint" "BR-MS-BRAND-002" \
    "PUT" "$BASE_URL/stores/$STORE_CODE/template" \
    '{"template":"december"}' \
    "200"

assert_json_field 51 "Branding response carries store_template" "BR-MS-BRAND-002" \
    "PUT" "$BASE_URL/stores/$STORE_CODE/template" \
    '{"template":"december"}' \
    '"store_template":"december"'

# Contract-conformance: required 'template' field omitted -> 422 (boundary rejection).
assert_status 52 "Set template without required 'template' field is rejected" "BR-MS-BRAND-002" \
    "PUT" "$BASE_URL/stores/$STORE_CODE/template" \
    '{}' \
    "422"

# ============================================
# SECTION 7: BR-MS-LAND — Landing content orchestration (1 rule)
# ============================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 7: BR-MS-LAND — Landing content orchestration (1 rule)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-MS-LAND-001: landing content provisioned via reserved landing section ---
# Success: save landing -> 200 provisioning the reserved landing section.
assert_status_and_capture 53 "Save store landing (provision reserved landing section)" "BR-MS-LAND-001" \
    "PUT" "$BASE_URL/stores/$STORE_CODE/landing" \
    '{"descriptions":[{"language_code":"en","title":"Welcome","home_page_content":"<h1>Welcome to Acme</h1>"}]}' \
    "200"

# Response-shape fidelity: landing carries the reserved landing_code.
assert_json_field 54 "Landing response carries reserved landing_code" "BR-MS-LAND-001" \
    "GET" "$BASE_URL/stores/$STORE_CODE/landing" \
    "null" \
    '"landing_code"'

# Contract-conformance: descriptions must have >=1 item -> empty rejected 422.
assert_status 55 "Reject landing save with empty descriptions (>=1 required)" "BR-MS-LAND-001" \
    "PUT" "$BASE_URL/stores/$STORE_CODE/landing" \
    '{"descriptions":[]}' \
    "422"

# Error: landing save for a nonexistent store -> 404.
assert_status 56 "Landing save for nonexistent store returns 404" "BR-MS-LAND-001" \
    "PUT" "$BASE_URL/stores/ghost_store_$SFX/landing" \
    '{"descriptions":[{"language_code":"en","title":"Welcome"}]}' \
    "404"

# ============================================
# SUMMARY
# ============================================
echo ""
echo "================================================================"
echo "TEST SUMMARY"
echo "================================================================"
echo ""
echo -e "${CYAN}Total Tests:  $TOTAL${NC}"
echo -e "${GREEN}Passed:       $PASSED${NC}"
echo -e "${RED}Failed:       $FAILED${NC}"
echo ""

if [ $FAILED -gt 0 ]; then
    echo -e "${RED}Failed Tests:${NC}"
    for test in "${FAILED_TESTS[@]}"; do
        echo "  ✗ $test"
    done
    echo ""
fi

if [ $TOTAL -gt 0 ]; then
    echo "Success Rate: $((PASSED * 100 / TOTAL))%"
fi

echo ""
if [ $FAILED -eq 0 ]; then
    echo -e "${GREEN}✅ ALL $TOTAL TESTS PASSED — 100% SUCCESS${NC}"
    exit 0
else
    echo -e "${RED}❌ $FAILED OF $TOTAL TESTS FAILED${NC}"
    exit 1
fi
