#!/bin/bash

# ============================================================================
# Comprehensive Test Suite for Customer Service (MS-05) v2.0
# Tests ALL 43 Business Rules:
#   BR-CUST-001 .. BR-CUST-028   (28 rules)
#   BR-CUSTOPT-001 .. BR-CUSTOPT-015 (15 rules)
# ALL tests execute against the running service - ZERO SKIPS
# Generated by SAAM Framework
#
# NAMING AUTHORITY: spec/microservices/MS-05/04-api-contract.yaml
#   - snake_case field names, kebab-case paths, PascalCase enum values
#   - Global headers: x-tenant-id, x-store-id (both required)
#   - Error shape (shared ErrorResponse): { error, message, status_code }
#
# Special rules honored:
#   - BR-CUST-026 (4a Decision: fix-on-migration) — REST-created shopper MUST be
#     placed in the CUSTOMER group (NOT admin). This is the FIXED behavior.
#   - BR-CUST-027 (configurable gender) — gender is optional on create; omitting it
#     succeeds. We do NOT assert a hardcoded 'M'.
#   - PLACE-004 / BR-CUSTOPT-013 (db ON DELETE CASCADE) — deleting a customer option
#     cascades to attributes/option-sets (assert the cascade EFFECT).
# ============================================================================

BASE_URL="http://localhost:8005/api/v1"
HEALTH_URL="http://localhost:8005/health"

PASSED=0
FAILED=0
TOTAL=0

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

declare -a FAILED_TESTS

# ============================================
# Global Headers (from API contract x-global-headers — applies to ALL requests)
# ============================================
TENANT_HEADER="x-tenant-id: test-tenant-001"
STORE_HEADER="x-store-id: test-store-001"
# A second store used for cross-store isolation checks (BR-CUST-018/024).
STORE_HEADER_OTHER="x-store-id: test-store-002"

# ============================================
# Helper Functions
# ============================================

# Extract a top-level field from a JSON response.
# NEVER use grep for ID extraction — nested objects may serialize before the root ID.
extract_field() {
    local json=$1
    local field=$2
    if command -v jq &>/dev/null; then
        echo "$json" | jq -r ".$field"
    else
        echo "$json" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('$field',''))"
    fi
}

# Capture BOTH status code AND response body in a single request.
# Sets globals: LAST_STATUS and LAST_BODY. Optional 4th arg overrides the store header.
capture_with_status() {
    local http_method=$1
    local url=$2
    local payload=$3
    local store_hdr=${4:-$STORE_HEADER}
    local response

    if [ -n "$payload" ] && [ "$payload" != "null" ]; then
        response=$(curl -s -w "\n%{http_code}" -X "$http_method" "$url" \
            -H 'Content-Type: application/json' -H "$TENANT_HEADER" -H "$store_hdr" -d "$payload")
    else
        response=$(curl -s -w "\n%{http_code}" -X "$http_method" "$url" \
            -H "$TENANT_HEADER" -H "$store_hdr")
    fi

    LAST_STATUS=$(echo "$response" | tail -1)
    LAST_BODY=$(echo "$response" | sed '$d')
}

# Assert exact HTTP status (contract fidelity). Optional 8th arg overrides the store header.
assert_status() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local expected_status=$7
    local store_hdr=${8:-$STORE_HEADER}

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected Status: $expected_status"

    capture_with_status "$http_method" "$url" "$payload" "$store_hdr"

    if [ "$LAST_STATUS" = "$expected_status" ]; then
        echo -e "  ${GREEN}PASSED${NC} (HTTP $LAST_STATUS)"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}FAILED${NC} (Expected: $expected_status, Got: $LAST_STATUS)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Expected $expected_status, Got $LAST_STATUS")
        return 1
    fi
}

# Assert exact HTTP status AND capture body for follow-on extraction (single request).
assert_status_and_capture() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local expected_status=$7
    local store_hdr=${8:-$STORE_HEADER}

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected Status: $expected_status"

    capture_with_status "$http_method" "$url" "$payload" "$store_hdr"

    if [ "$LAST_STATUS" = "$expected_status" ]; then
        echo -e "  ${GREEN}PASSED${NC} (HTTP $LAST_STATUS)"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}FAILED${NC} (Expected: $expected_status, Got: $LAST_STATUS)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Expected $expected_status, Got $LAST_STATUS")
        return 1
    fi
}

# Assert a JSON field/pattern is present in the response body of a fresh request.
# Optional 8th arg overrides the store header.
assert_json_field() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local json_pattern=$7
    local store_hdr=${8:-$STORE_HEADER}

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected pattern: $json_pattern"

    capture_with_status "$http_method" "$url" "$payload" "$store_hdr"

    if echo "$LAST_BODY" | grep -qF "$json_pattern"; then
        echo -e "  ${GREEN}PASSED${NC}"
        PASSED=$((PASSED + 1))
        return 0
    else
        echo -e "  ${RED}FAILED${NC}"
        echo "  Expected pattern: $json_pattern"
        echo "  Got: $(echo "$LAST_BODY" | head -c 300)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Pattern '$json_pattern' not found")
        return 1
    fi
}

# Assert a JSON field/pattern is ABSENT (used e.g. for password-never-returned).
assert_json_absent() {
    local test_num=$1
    local test_name=$2
    local rule_id=$3
    local http_method=$4
    local url=$5
    local payload=$6
    local json_pattern=$7
    local store_hdr=${8:-$STORE_HEADER}

    TOTAL=$((TOTAL + 1))
    echo -e "\n${BLUE}Test $test_num: $test_name${NC}"
    echo -e "  Rule: $rule_id | Expected ABSENT: $json_pattern"

    capture_with_status "$http_method" "$url" "$payload" "$store_hdr"

    if echo "$LAST_BODY" | grep -qF "$json_pattern"; then
        echo -e "  ${RED}FAILED${NC} (pattern present but should be absent)"
        echo "  Got: $(echo "$LAST_BODY" | head -c 300)"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("Test $test_num: $test_name [$rule_id] - Pattern '$json_pattern' should be absent")
        return 1
    else
        echo -e "  ${GREEN}PASSED${NC}"
        PASSED=$((PASSED + 1))
        return 0
    fi
}

echo "=============================================="
echo "Customer Service (MS-05) - Comprehensive Test Suite v2.0"
echo "ALL 43 Business Rules - ZERO SKIPS"
echo "=============================================="

# Pre-flight check — HEALTH_URL is absolute, NOT derived from BASE_URL.
echo -e "${YELLOW}Pre-flight: Checking service availability...${NC}"
if ! curl -s -f "$HEALTH_URL" > /dev/null 2>&1; then
    if ! curl -s -o /dev/null -w '%{http_code}' "$BASE_URL/customers" -H "$TENANT_HEADER" -H "$STORE_HEADER" | grep -q "200\|401\|403"; then
        echo -e "${RED}ERROR: Service not running at $BASE_URL (health: $HEALTH_URL)${NC}"
        exit 1
    fi
fi
echo -e "${GREEN}Service is running (health: $HEALTH_URL)${NC}"

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

# Unique-ish suffix so re-runs against a non-reset DB collide less on unique codes/usernames.
SFX="$$"

# ============================================================================
# SECTION 1: Shopper identity, uniqueness & lookup (BR-CUST-001, 002, 015, 024)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 1: Shopper identity, uniqueness & lookup${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-CUST-001: username unique within a store; lookup resolves by (username, store) ---
assert_status_and_capture 1 "Create shopper for lookup" "BR-CUST-001" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"jsmith_$SFX\",\"email_address\":\"jsmith_$SFX@x.com\",\"password\":\"secret1\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"
CUST_ID=$(extract_field "$LAST_BODY" "id")

assert_json_field 2 "Lookup shopper by user_name in store" "BR-CUST-001" \
    "GET" "$BASE_URL/customers/lookup?user_name=jsmith_$SFX" "null" \
    "\"user_name\":\"jsmith_$SFX\""

assert_status 3 "Lookup unknown user_name returns 404" "BR-CUST-001" \
    "GET" "$BASE_URL/customers/lookup?user_name=nobody_$SFX" "null" "404"

# --- BR-CUST-002: registration rejects a username already taken in the same store ---
assert_status 4 "Register with fresh username succeeds" "BR-CUST-002" \
    "POST" "$BASE_URL/customers/registration" \
    "{\"user_name\":\"reg_$SFX\",\"password\":\"secret1\",\"check_password\":\"secret1\",\"email_address\":\"reg_$SFX@x.com\"}" \
    "201"

assert_status 5 "Register with duplicate username in same store rejected (409)" "BR-CUST-002" \
    "POST" "$BASE_URL/customers/registration" \
    "{\"user_name\":\"reg_$SFX\",\"password\":\"secret1\",\"check_password\":\"secret1\",\"email_address\":\"reg2_$SFX@x.com\"}" \
    "409"

# --- BR-CUST-015: persist creates when new, updates when existing (upsert by identity) ---
assert_status 6 "Update existing shopper (PUT) succeeds" "BR-CUST-015" \
    "PUT" "$BASE_URL/customers/$CUST_ID" \
    "{\"email_address\":\"jsmith_upd_$SFX@x.com\",\"company\":\"Acme\"}" \
    "200"

assert_status 7 "Update non-existent shopper returns 404" "BR-CUST-015" \
    "PUT" "$BASE_URL/customers/00000000-0000-0000-0000-000000000000" \
    "{\"email_address\":\"z@x.com\"}" "404"

# --- BR-CUST-024: store-scoped operations resolve/validate the store from the request ---
assert_status 8 "Get shopper within owning store succeeds" "BR-CUST-024" \
    "GET" "$BASE_URL/customers/$CUST_ID" "null" "200"

# ============================================================================
# SECTION 2: Registration validation (BR-CUST-003, 017, 020)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 2: Registration validation${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-CUST-003: password and its confirmation must match ---
assert_status 9 "Registration with matching password/check succeeds" "BR-CUST-003" \
    "POST" "$BASE_URL/customers/registration" \
    "{\"user_name\":\"pw_$SFX\",\"password\":\"secret1\",\"check_password\":\"secret1\",\"email_address\":\"pw_$SFX@x.com\"}" \
    "201"

assert_status 10 "Registration with mismatched confirmation rejected (422)" "BR-CUST-003" \
    "POST" "$BASE_URL/customers/registration" \
    "{\"user_name\":\"pwbad_$SFX\",\"password\":\"secret1\",\"check_password\":\"secret2\",\"email_address\":\"pwbad_$SFX@x.com\"}" \
    "422"

# --- BR-CUST-017: administrative/email validation applies (invalid email rejected) ---
assert_status 11 "Create with well-formed email succeeds" "BR-CUST-017" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"mail_$SFX\",\"email_address\":\"mail_$SFX@x.com\",\"password\":\"secret1\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"

assert_status 12 "Create with malformed email rejected (422)" "BR-CUST-017" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"mailbad_$SFX\",\"email_address\":\"not-an-email\",\"password\":\"secret1\"}" \
    "422"

# --- BR-CUST-020: human-verification challenge validated when supplied ---
assert_status 13 "Registration without captcha fields skips the check (201)" "BR-CUST-020" \
    "POST" "$BASE_URL/customers/registration" \
    "{\"user_name\":\"cap_$SFX\",\"password\":\"secret1\",\"check_password\":\"secret1\",\"email_address\":\"cap_$SFX@x.com\"}" \
    "201"

assert_status 14 "Registration with invalid captcha response rejected (422)" "BR-CUST-020" \
    "POST" "$BASE_URL/customers/registration" \
    "{\"user_name\":\"capbad_$SFX\",\"password\":\"secret1\",\"check_password\":\"secret1\",\"email_address\":\"capbad_$SFX@x.com\",\"captcha_challenge\":\"c\",\"captcha_response\":\"invalid\"}" \
    "422"

# ============================================================================
# SECTION 3: Password handling & credentials (BR-CUST-004, 006, 016, 025)
#            + Layer A INV-CUST-003 (password never cleartext)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 3: Password handling & credentials${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

assert_status_and_capture 15 "Create shopper with a password" "BR-CUST-004" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"pwstore_$SFX\",\"email_address\":\"pwstore_$SFX@x.com\",\"password\":\"secret1\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"
PW_CUST_ID=$(extract_field "$LAST_BODY" "id")

# --- BR-CUST-004 / INV-CUST-003 (Layer A): password never returned in cleartext ---
assert_json_absent 16 "Create response never exposes the clear password" "BR-CUST-004" \
    "GET" "$BASE_URL/customers/$PW_CUST_ID" "null" "secret1"

assert_json_absent 17 "Read-back never exposes a password field at all" "BR-CUST-004" \
    "GET" "$BASE_URL/customers/$PW_CUST_ID" "null" "\"password\""

# --- BR-CUST-006: a new/blank-password shopper gets a generated encoded password ---
assert_status 18 "Create shopper with no password succeeds (generated encoded pw)" "BR-CUST-006" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"nopw_$SFX\",\"email_address\":\"nopw_$SFX@x.com\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"

# --- BR-CUST-016: changing a password requires the current password to match ---
assert_status 19 "Change password with correct current succeeds (200)" "BR-CUST-016" \
    "POST" "$BASE_URL/customers/$PW_CUST_ID/password" \
    "{\"current_password\":\"secret1\",\"password\":\"secret2\"}" "200"

assert_status 20 "Change password with wrong current rejected (422)" "BR-CUST-016" \
    "POST" "$BASE_URL/customers/$PW_CUST_ID/password" \
    "{\"current_password\":\"wrong\",\"password\":\"secret3\"}" "422"

# --- BR-CUST-025: administrative password reset ---
assert_status 21 "Administrative password reset succeeds (200)" "BR-CUST-025" \
    "POST" "$BASE_URL/customers/$PW_CUST_ID/password-reset" "null" "200"

assert_status 22 "Password reset for unknown shopper returns 404" "BR-CUST-025" \
    "POST" "$BASE_URL/customers/00000000-0000-0000-0000-000000000000/password-reset" "null" "404"

# ============================================================================
# SECTION 4: Defaults & state transitions (BR-CUST-005, 007, 010, 014, 027, 026)
#            behavioral: register -> read back; fixed group placement; configurable gender
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 4: Defaults & state transitions${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-CUST-005: blank username -> generated 6-char username ---
assert_status_and_capture 23 "Create shopper with no user_name (generated username)" "BR-CUST-005" \
    "POST" "$BASE_URL/customers" \
    "{\"email_address\":\"gen_$SFX@x.com\",\"password\":\"secret1\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"
GEN_CUST_ID=$(extract_field "$LAST_BODY" "id")
assert_json_field 24 "Generated shopper has a non-empty user_name" "BR-CUST-005" \
    "GET" "$BASE_URL/customers/$GEN_CUST_ID" "null" "\"user_name\""

# --- BR-CUST-007: no group -> standard shopper (CUSTOMER) group (self-service path) ---
assert_status_and_capture 25 "Self-service registration (behavioral: read back)" "BR-CUST-007" \
    "POST" "$BASE_URL/customers/registration" \
    "{\"user_name\":\"grp_$SFX\",\"password\":\"secret1\",\"check_password\":\"secret1\",\"email_address\":\"grp_$SFX@x.com\"}" \
    "201"
GRP_CUST_ID=$(extract_field "$LAST_BODY" "id")
assert_json_field 26 "Registered shopper has group membership (default shopper group)" "BR-CUST-007" \
    "GET" "$BASE_URL/customers/$GRP_CUST_ID/groups" "null" "\"items\""

# --- BR-CUST-010: setting a real password marks the shopper non-anonymous (state transition) ---
assert_json_field 27 "Shopper created with a password is non-anonymous" "BR-CUST-010" \
    "GET" "$BASE_URL/customers/$PW_CUST_ID" "null" "\"anonymous\":false"

# --- BR-CUST-014: language defaults to the store default when unresolved ---
assert_status_and_capture 28 "Create with unresolvable language falls back to store default" "BR-CUST-014" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"lang_$SFX\",\"email_address\":\"lang_$SFX@x.com\",\"password\":\"secret1\",\"language\":\"zz\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"
LANG_CUST_ID=$(extract_field "$LAST_BODY" "id")
assert_json_field 29 "Shopper has a resolved language after fallback" "BR-CUST-014" \
    "GET" "$BASE_URL/customers/$LANG_CUST_ID" "null" "\"language\""

# --- BR-CUST-027: gender optional; create WITHOUT gender succeeds; no hardcoded 'M' asserted ---
assert_status 30 "Create shopper WITHOUT gender succeeds (gender optional)" "BR-CUST-027" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"nog_$SFX\",\"email_address\":\"nog_$SFX@x.com\",\"password\":\"secret1\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"

# --- BR-CUST-026 (4a fix-on-migration): REST-created shopper placed in CUSTOMER group, NOT admin ---
assert_status_and_capture 31 "Create shopper via service (REST) path" "BR-CUST-026" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"rest_$SFX\",\"email_address\":\"rest_$SFX@x.com\",\"password\":\"secret1\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"
REST_CUST_ID=$(extract_field "$LAST_BODY" "id")
assert_json_absent 32 "FIXED behavior: REST-created shopper is NOT in the ADMIN group" "BR-CUST-026" \
    "GET" "$BASE_URL/customers/$REST_CUST_ID/groups" "null" "ADMIN"
assert_json_field 33 "FIXED behavior: REST-created shopper HAS a (customer) group membership" "BR-CUST-026" \
    "GET" "$BASE_URL/customers/$REST_CUST_ID/groups" "null" "\"items\""

# ============================================================================
# SECTION 5: Authentication & login (BR-CUST-008, 009, 022)
#            behavioral: login flow + uniform failure + session-cart merge
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 5: Authentication & login${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# Register a known shopper to log in with.
capture_with_status "POST" "$BASE_URL/customers/registration" \
    "{\"user_name\":\"login_$SFX\",\"password\":\"secret1\",\"check_password\":\"secret1\",\"email_address\":\"login_$SFX@x.com\"}"

# --- BR-CUST-008: authorities combine base role + group permissions ---
assert_json_field 34 "Login returns authorities array" "BR-CUST-008" \
    "POST" "$BASE_URL/customers/login" \
    "{\"user_name\":\"login_$SFX\",\"password\":\"secret1\"}" \
    "\"authorities\""

# --- BR-CUST-009: uniform failure when user does not exist for (username, store) ---
assert_status 35 "Login with correct credentials succeeds (200)" "BR-CUST-009" \
    "POST" "$BASE_URL/customers/login" \
    "{\"user_name\":\"login_$SFX\",\"password\":\"secret1\"}" "200"

assert_status 36 "Login with unknown username fails uniformly (401)" "BR-CUST-009" \
    "POST" "$BASE_URL/customers/login" \
    "{\"user_name\":\"ghost_$SFX\",\"password\":\"x\"}" "401"

assert_status 37 "Login with wrong password fails the same way (401)" "BR-CUST-009" \
    "POST" "$BASE_URL/customers/login" \
    "{\"user_name\":\"login_$SFX\",\"password\":\"wrong\"}" "401"

# --- BR-CUST-022: anonymous session cart merged into the shopper's cart on login ---
assert_json_field 38 "Login with session_cart_code returns a cart_code" "BR-CUST-022" \
    "POST" "$BASE_URL/customers/login" \
    "{\"user_name\":\"login_$SFX\",\"password\":\"secret1\",\"session_cart_code\":\"CART-XYZ\"}" \
    "\"cart_code\""

# ============================================================================
# SECTION 6: Addresses & invariants (BR-CUST-011, 012, 013, 019)
#            Layer A: address zone-xor-state (INV-CUST-006)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 6: Addresses & address invariants${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-CUST-011: billing address requires name, street, city, postal code, country ---
assert_status 39 "Update billing with full valid address succeeds (200)" "BR-CUST-011" \
    "PUT" "$BASE_URL/customers/$CUST_ID/addresses/billing" \
    "{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\",\"zone\":\"NY\"}" \
    "200"

assert_status 40 "Update billing missing address+postal_code rejected (422)" "BR-CUST-011" \
    "PUT" "$BASE_URL/customers/$CUST_ID/addresses/billing" \
    "{\"first_name\":\"J\",\"last_name\":\"S\",\"city\":\"NY\",\"country\":\"US\"}" \
    "422"

# --- BR-CUST-012: delivery address is optional ---
assert_status 41 "Get delivery address (optional) returns 200 or 404" "BR-CUST-012" \
    "GET" "$BASE_URL/customers/$CUST_ID/addresses/delivery" "null" "404"

assert_status 42 "Update delivery with unknown country rejected (422)" "BR-CUST-012" \
    "PUT" "$BASE_URL/customers/$CUST_ID/addresses/delivery" \
    "{\"country\":\"ZZ\"}" "422"

# --- BR-CUST-013: country/zone must resolve to known reference data ---
assert_status 43 "Update billing with unknown zone rejected (422)" "BR-CUST-013" \
    "PUT" "$BASE_URL/customers/$CUST_ID/addresses/billing" \
    "{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\",\"zone\":\"ZZZ\"}" \
    "422"

# --- BR-CUST-019 / INV-CUST-006 (Layer A): zone and free-text state are mutually exclusive ---
assert_json_field 44 "Zone-country: setting zone clears free-text state (state=null)" "BR-CUST-019" \
    "PUT" "$BASE_URL/customers/$CUST_ID/addresses/billing" \
    "{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\",\"zone\":\"NY\"}" \
    "\"state\":null"

assert_status 45 "Zone-country with state but missing required zone rejected (422)" "BR-CUST-019" \
    "PUT" "$BASE_URL/customers/$CUST_ID/addresses/billing" \
    "{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\",\"state\":\"Freetext\"}" \
    "422"

# ============================================================================
# SECTION 7: Groups (BR-CUST-023)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 7: Group membership${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-CUST-023: membership recorded only; group catalog never created/deleted via shopper ---
assert_status 46 "Add a group membership to a shopper (200)" "BR-CUST-023" \
    "POST" "$BASE_URL/customers/$CUST_ID/groups" \
    "{\"group_id\":3}" "200"

assert_status 47 "Add unknown group id rejected (422)" "BR-CUST-023" \
    "POST" "$BASE_URL/customers/$CUST_ID/groups" \
    "{\"group_id\":999999}" "422"

assert_status 48 "Remove a group membership (204)" "BR-CUST-023" \
    "DELETE" "$BASE_URL/customers/$CUST_ID/groups/3" "null" "204"

# ============================================================================
# SECTION 8: Store isolation (BR-CUST-018)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 8: Store isolation${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-CUST-018: a resource is operable only within its owning store ---
assert_status 49 "Read shopper within owning store succeeds (200)" "BR-CUST-018" \
    "GET" "$BASE_URL/customers/$CUST_ID" "null" "200" "$STORE_HEADER"

assert_status 50 "Read same shopper from a DIFFERENT store returns 404" "BR-CUST-018" \
    "GET" "$BASE_URL/customers/$CUST_ID" "null" "404" "$STORE_HEADER_OTHER"

# ============================================================================
# SECTION 9: Delete cascade for shopper (BR-CUST-028)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 9: Shopper delete cascade${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-CUST-028: deleting a shopper cascades removal of that shopper's attributes ---
assert_status_and_capture 51 "Create a shopper to delete" "BR-CUST-028" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"del_$SFX\",\"email_address\":\"del_$SFX@x.com\",\"password\":\"secret1\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"
DEL_CUST_ID=$(extract_field "$LAST_BODY" "id")

assert_status 52 "Delete the shopper (204)" "BR-CUST-028" \
    "DELETE" "$BASE_URL/customers/$DEL_CUST_ID" "null" "204"

assert_status 53 "Deleted shopper is gone (GET -> 404)" "BR-CUST-028" \
    "GET" "$BASE_URL/customers/$DEL_CUST_ID" "null" "404"

assert_status 54 "Deleted shopper attributes are gone (cascade; list -> 404)" "BR-CUST-028" \
    "GET" "$BASE_URL/customers/$DEL_CUST_ID/attributes" "null" "404"

# ============================================================================
# SECTION 10: Customer options (BR-CUSTOPT-001, 002, 003, 009)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 10: Customer options${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-CUSTOPT-001: option code unique within a store ---
assert_status_and_capture 55 "Create a customer option (Text type)" "BR-CUSTOPT-001" \
    "POST" "$BASE_URL/customer-options" \
    "{\"code\":\"OPT_$SFX\",\"type\":\"Text\",\"active\":true,\"public\":true,\"descriptions\":[{\"language\":\"en\",\"name\":\"Opt\"}]}" \
    "201"
OPT_ID=$(extract_field "$LAST_BODY" "id")

assert_status 56 "Duplicate option code in same store rejected (409)" "BR-CUSTOPT-001" \
    "POST" "$BASE_URL/customer-options" \
    "{\"code\":\"OPT_$SFX\",\"type\":\"Text\",\"descriptions\":[{\"language\":\"en\",\"name\":\"Opt2\"}]}" \
    "409"

# --- BR-CUSTOPT-002: option code alphanumeric/underscore, non-empty ---
assert_status 57 "Option code with illegal characters rejected (422)" "BR-CUSTOPT-002" \
    "POST" "$BASE_URL/customer-options" \
    "{\"code\":\"bad code!\",\"type\":\"Select\",\"descriptions\":[{\"language\":\"en\",\"name\":\"X\"}]}" \
    "422"

# --- BR-CUSTOPT-003: option requires a non-blank name per language ---
assert_status 58 "Option with blank description name rejected (422)" "BR-CUSTOPT-003" \
    "POST" "$BASE_URL/customer-options" \
    "{\"code\":\"OPTBLANK_$SFX\",\"type\":\"Checkbox\",\"descriptions\":[{\"language\":\"en\",\"name\":\"\"}]}" \
    "422"

# --- BR-CUSTOPT-009: option persistence creates when new, updates when existing ---
assert_status 59 "Update existing option (200)" "BR-CUSTOPT-009" \
    "PUT" "$BASE_URL/customer-options/$OPT_ID" \
    "{\"code\":\"OPT_$SFX\",\"type\":\"Text\",\"active\":true,\"public\":true,\"descriptions\":[{\"language\":\"en\",\"name\":\"Opt Updated\"}]}" \
    "200"

assert_status 60 "Update non-existent option returns 404" "BR-CUSTOPT-009" \
    "PUT" "$BASE_URL/customer-options/00000000-0000-0000-0000-000000000000" \
    "{\"code\":\"NOPE_$SFX\",\"descriptions\":[{\"language\":\"en\",\"name\":\"N\"}]}" \
    "404"

# ============================================================================
# SECTION 11: Option values & option-sets (BR-CUSTOPT-004, 005, 006, 007, 008)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 11: Option values & option-sets${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-CUSTOPT-004: option value code unique within a store ---
assert_status_and_capture 61 "Create a customer option value" "BR-CUSTOPT-004" \
    "POST" "$BASE_URL/customer-option-values" \
    "{\"code\":\"VAL_$SFX\",\"descriptions\":[{\"language\":\"en\",\"name\":\"Weekly\"}]}" \
    "201"
VAL_ID=$(extract_field "$LAST_BODY" "id")

assert_status 62 "Duplicate value code in same store rejected (409)" "BR-CUSTOPT-004" \
    "POST" "$BASE_URL/customer-option-values" \
    "{\"code\":\"VAL_$SFX\",\"descriptions\":[{\"language\":\"en\",\"name\":\"Dup\"}]}" \
    "409"

# --- BR-CUSTOPT-005: option value code alphanumeric/underscore, non-empty ---
assert_status 63 "Option value code with illegal characters rejected (422)" "BR-CUSTOPT-005" \
    "POST" "$BASE_URL/customer-option-values" \
    "{\"code\":\"weekly!\",\"descriptions\":[{\"language\":\"en\",\"name\":\"X\"}]}" \
    "422"

# --- BR-CUSTOPT-006: value requires at least one non-blank description ---
assert_status 64 "Option value with empty descriptions rejected (422)" "BR-CUSTOPT-006" \
    "POST" "$BASE_URL/customer-option-values" \
    "{\"code\":\"VALEMPTY_$SFX\",\"descriptions\":[]}" \
    "422"

# --- BR-CUSTOPT-007: option-set requires both an option and a value ---
assert_status_and_capture 65 "Create option-set binding (option,value) succeeds (201)" "BR-CUSTOPT-007" \
    "POST" "$BASE_URL/customer-option-sets" \
    "{\"option_id\":\"$OPT_ID\",\"option_value_id\":\"$VAL_ID\"}" \
    "201"
SET_ID=$(extract_field "$LAST_BODY" "id")

assert_status 66 "Option-set missing the value is rejected (422)" "BR-CUSTOPT-007" \
    "POST" "$BASE_URL/customer-option-sets" \
    "{\"option_id\":\"$OPT_ID\"}" \
    "422"

# --- BR-CUSTOPT-008: (option,value) binding unique within a store ---
assert_status 67 "Duplicate (option,value) binding rejected (409)" "BR-CUSTOPT-008" \
    "POST" "$BASE_URL/customer-option-sets" \
    "{\"option_id\":\"$OPT_ID\",\"option_value_id\":\"$VAL_ID\"}" \
    "409"

# ============================================================================
# SECTION 12: Per-shopper attributes (BR-CUSTOPT-010, 011, 012, 015)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 12: Per-shopper attributes${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# Create a shopper + a Text option and a choice option for attribute tests.
assert_status_and_capture 68 "Create shopper for attribute tests" "BR-CUSTOPT-010" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"attr_$SFX\",\"email_address\":\"attr_$SFX@x.com\",\"password\":\"secret1\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"
ATTR_CUST_ID=$(extract_field "$LAST_BODY" "id")

# --- BR-CUSTOPT-010: attribute's option and value must exist and belong to the store ---
assert_status 69 "Reconcile attributes with valid option/value succeeds (200)" "BR-CUSTOPT-010" \
    "PUT" "$BASE_URL/customers/$ATTR_CUST_ID/attributes" \
    "{\"attributes\":[{\"option_id\":\"$OPT_ID\",\"option_value_id\":\"$VAL_ID\"}]}" \
    "200"

assert_status 70 "Attribute referencing unknown option rejected (422)" "BR-CUSTOPT-010" \
    "PUT" "$BASE_URL/customers/$ATTR_CUST_ID/attributes" \
    "{\"attributes\":[{\"option_id\":\"00000000-0000-0000-0000-000000000000\",\"option_value_id\":\"$VAL_ID\"}]}" \
    "422"

# --- BR-CUSTOPT-011: text option stores free text; choice option stores selected value ---
assert_status_and_capture 71 "Create a Text-type option for free-text attribute" "BR-CUSTOPT-011" \
    "POST" "$BASE_URL/customer-options" \
    "{\"code\":\"OPTTXT_$SFX\",\"type\":\"Text\",\"active\":true,\"public\":true,\"descriptions\":[{\"language\":\"en\",\"name\":\"Color\"}]}" \
    "201"
OPTTXT_ID=$(extract_field "$LAST_BODY" "id")
assert_json_field 72 "Text attribute stores free text (text_value present)" "BR-CUSTOPT-011" \
    "PUT" "$BASE_URL/customers/$ATTR_CUST_ID/attributes" \
    "{\"attributes\":[{\"option_id\":\"$OPTTXT_ID\",\"text_value\":\"blue\"}]}" \
    "\"text_value\":\"blue\""

# --- BR-CUSTOPT-012: reconcile — create/update/delete unselected; one attribute per option ---
assert_status_and_capture 73 "Reconcile attributes to a single option (drops others)" "BR-CUSTOPT-012" \
    "PUT" "$BASE_URL/customers/$ATTR_CUST_ID/attributes" \
    "{\"attributes\":[{\"option_id\":\"$OPT_ID\",\"option_value_id\":\"$VAL_ID\"}]}" \
    "200"
assert_json_absent 74 "Unresubmitted text attribute was deleted (reconcile)" "BR-CUSTOPT-012" \
    "GET" "$BASE_URL/customers/$ATTR_CUST_ID/attributes" "null" "\"text_value\":\"blue\""

# --- BR-CUSTOPT-015: only active+public options shown to shoppers ---
assert_json_field 75 "Available-options list returns items for the shopper" "BR-CUSTOPT-015" \
    "GET" "$BASE_URL/customers/$ATTR_CUST_ID/available-options" "null" "\"items\""

assert_status 76 "Available-options for a shopper outside the store returns 404" "BR-CUSTOPT-015" \
    "GET" "$BASE_URL/customers/$ATTR_CUST_ID/available-options" "null" "404" "$STORE_HEADER_OTHER"

# ============================================================================
# SECTION 13: Option/value delete cascade — PLACE-004 db ON DELETE CASCADE
#             (BR-CUSTOPT-013, BR-CUSTOPT-014)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 13: Option/value delete cascade (PLACE-004)${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# --- BR-CUSTOPT-013 / PLACE-004: deleting an option cascades to attributes & option-sets ---
# Build a fresh option + value + option-set + shopper attribute, delete the option,
# then assert the dependent attribute (and binding) are gone (DB cascade effect).
assert_status_and_capture 77 "Create option for cascade test" "BR-CUSTOPT-013" \
    "POST" "$BASE_URL/customer-options" \
    "{\"code\":\"OPTCASC_$SFX\",\"type\":\"Text\",\"active\":true,\"public\":true,\"descriptions\":[{\"language\":\"en\",\"name\":\"Casc\"}]}" \
    "201"
CASC_OPT_ID=$(extract_field "$LAST_BODY" "id")

assert_status_and_capture 78 "Create value for cascade test" "BR-CUSTOPT-013" \
    "POST" "$BASE_URL/customer-option-values" \
    "{\"code\":\"VALCASC_$SFX\",\"descriptions\":[{\"language\":\"en\",\"name\":\"CascVal\"}]}" \
    "201"
CASC_VAL_ID=$(extract_field "$LAST_BODY" "id")

assert_status 79 "Bind (option,value) for cascade test (201)" "BR-CUSTOPT-013" \
    "POST" "$BASE_URL/customer-option-sets" \
    "{\"option_id\":\"$CASC_OPT_ID\",\"option_value_id\":\"$CASC_VAL_ID\"}" \
    "201"

# Attach an attribute on the cascade option to a shopper.
assert_status 80 "Attach shopper attribute using the cascade option (200)" "BR-CUSTOPT-013" \
    "PUT" "$BASE_URL/customers/$ATTR_CUST_ID/attributes" \
    "{\"attributes\":[{\"option_id\":\"$CASC_OPT_ID\",\"text_value\":\"casc\"}]}" \
    "200"

# Delete the option — the DB ON DELETE CASCADE removes dependent attributes & bindings.
assert_status 81 "Delete the customer option (204)" "BR-CUSTOPT-013" \
    "DELETE" "$BASE_URL/customer-options/$CASC_OPT_ID" "null" "204"

# Assert the cascade EFFECT: the shopper's attribute for that option is gone.
assert_json_absent 82 "Cascade effect: shopper attribute for deleted option is gone" "BR-CUSTOPT-013" \
    "GET" "$BASE_URL/customers/$ATTR_CUST_ID/attributes" "null" "\"text_value\":\"casc\"" 

assert_status 83 "Deleted option is gone (GET -> 404)" "BR-CUSTOPT-013" \
    "GET" "$BASE_URL/customer-options/$CASC_OPT_ID" "null" "404"

# --- BR-CUSTOPT-014: deleting an option value cascades to attributes & option-sets ---
assert_status_and_capture 84 "Create option for value-cascade test" "BR-CUSTOPT-014" \
    "POST" "$BASE_URL/customer-options" \
    "{\"code\":\"OPTVC_$SFX\",\"type\":\"Select\",\"active\":true,\"public\":true,\"descriptions\":[{\"language\":\"en\",\"name\":\"VC\"}]}" \
    "201"
VC_OPT_ID=$(extract_field "$LAST_BODY" "id")

assert_status_and_capture 85 "Create value for value-cascade test" "BR-CUSTOPT-014" \
    "POST" "$BASE_URL/customer-option-values" \
    "{\"code\":\"VALVC_$SFX\",\"descriptions\":[{\"language\":\"en\",\"name\":\"VCVal\"}]}" \
    "201"
VC_VAL_ID=$(extract_field "$LAST_BODY" "id")

assert_status 86 "Bind (option,value) for value-cascade test (201)" "BR-CUSTOPT-014" \
    "POST" "$BASE_URL/customer-option-sets" \
    "{\"option_id\":\"$VC_OPT_ID\",\"option_value_id\":\"$VC_VAL_ID\"}" \
    "201"

assert_status 87 "Delete the customer option value (204)" "BR-CUSTOPT-014" \
    "DELETE" "$BASE_URL/customer-option-values/$VC_VAL_ID" "null" "204"

assert_status 88 "Deleted option value is gone (delete again -> 404)" "BR-CUSTOPT-014" \
    "DELETE" "$BASE_URL/customer-option-values/$VC_VAL_ID" "null" "404"

# ============================================================================
# SECTION 14: Lifecycle notification emails (BR-CUST-021)
#   Side effect: registration / password-change / password-reset each dispatch a
#   notification email. In the Test profile the mail port binds to an in-process
#   double, so the observable proxy is that each triggering operation succeeds
#   (the operation is what fires the email). We assert the trigger operations.
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 14: Lifecycle notification emails${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

assert_status_and_capture 99 "Registration triggers a notification email (201)" "BR-CUST-021" \
    "POST" "$BASE_URL/customers/registration" \
    "{\"user_name\":\"mailtrig_$SFX\",\"password\":\"secret1\",\"check_password\":\"secret1\",\"email_address\":\"mailtrig_$SFX@x.com\"}" \
    "201"
MAIL_CUST_ID=$(extract_field "$LAST_BODY" "id")

assert_status 100 "Password change triggers a notification email (200)" "BR-CUST-021" \
    "POST" "$BASE_URL/customers/$MAIL_CUST_ID/password" \
    "{\"current_password\":\"secret1\",\"password\":\"secret2\"}" "200"

assert_status 101 "Administrative password reset triggers a notification email (200)" "BR-CUST-021" \
    "POST" "$BASE_URL/customers/$MAIL_CUST_ID/password-reset" "null" "200"

# ============================================================================
# SECTION 15: Contract-conformance & Layer A invariants (cross-cutting)
# ============================================================================
echo ""
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"
echo -e "${CYAN}SECTION 15: Contract-conformance & Layer A invariants${NC}"
echo -e "${CYAN}══════════════════════════════════════════════════${NC}"

# Contract-conformance: list envelope shape { items, pagination }.
assert_json_field 89 "List customers returns paged envelope (items)" "BR-CUST-024" \
    "GET" "$BASE_URL/customers" "null" "\"items\""
assert_json_field 90 "List customers envelope includes pagination" "BR-CUST-024" \
    "GET" "$BASE_URL/customers" "null" "\"pagination\""

# Contract-conformance: optional page/page_size omitted still succeeds (200).
assert_status 91 "List customers with page params omitted succeeds (200)" "BR-CUST-024" \
    "GET" "$BASE_URL/customers" "null" "200"

# Contract-conformance: required query param omitted on lookup -> 400 (not 500).
assert_status 92 "Lookup without required user_name is a client error (400)" "BR-CUST-001" \
    "GET" "$BASE_URL/customers/lookup" "null" "400"

# Contract-conformance: status-code fidelity — create returns 201 (not 200).
assert_status 93 "Create customer returns 201 (status fidelity)" "BR-CUST-015" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"conf_$SFX\",\"email_address\":\"conf_$SFX@x.com\",\"password\":\"secret1\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"

# Contract-conformance: create with missing required email_address rejected (422, not 500).
assert_status 94 "Create with missing required email_address rejected (422)" "BR-CUST-011" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"noemail_$SFX\",\"password\":\"secret1\"}" \
    "422"

# Layer A INV-CUST-002: username unique per store (constraint) — enforced on create path.
assert_status 95 "INV-CUST-002: duplicate username in same store rejected (409)" "BR-CUST-002" \
    "POST" "$BASE_URL/customers/registration" \
    "{\"user_name\":\"reg_$SFX\",\"password\":\"secret1\",\"check_password\":\"secret1\",\"email_address\":\"reg3_$SFX@x.com\"}" \
    "409"

# Layer A INV-CUST-004: gender, when set, is Male or Female (enum M/F).
assert_status 96 "INV-CUST-004: valid gender M accepted (201)" "BR-CUST-027" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"genm_$SFX\",\"email_address\":\"genm_$SFX@x.com\",\"password\":\"secret1\",\"gender\":\"M\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"
assert_status 97 "INV-CUST-004: valid gender F accepted (201)" "BR-CUST-027" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"genf_$SFX\",\"email_address\":\"genf_$SFX@x.com\",\"password\":\"secret1\",\"gender\":\"F\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "201"
assert_status 98 "INV-CUST-004: invalid gender X rejected (422)" "BR-CUST-027" \
    "POST" "$BASE_URL/customers" \
    "{\"user_name\":\"genx_$SFX\",\"email_address\":\"genx_$SFX@x.com\",\"password\":\"secret1\",\"gender\":\"X\",\"billing\":{\"first_name\":\"J\",\"last_name\":\"S\",\"address\":\"1 St\",\"city\":\"NY\",\"postal_code\":\"10001\",\"country\":\"US\"}}" \
    "422"

# ============================================
# SUMMARY
# ============================================
echo ""
echo "================================================================"
echo "TEST SUMMARY — Customer Service (MS-05)"
echo "================================================================"
echo ""
echo -e "${CYAN}Total Tests:  $TOTAL${NC}"
echo -e "${GREEN}Passed:       $PASSED${NC}"
echo -e "${RED}Failed:       $FAILED${NC}"
echo ""

if [ $FAILED -gt 0 ]; then
    echo -e "${RED}Failed Tests:${NC}"
    for test in "${FAILED_TESTS[@]}"; do
        echo "  x $test"
    done
    echo ""
fi

if [ $TOTAL -gt 0 ]; then
    echo "Success Rate: $((PASSED * 100 / TOTAL))%"
fi

echo ""
if [ $FAILED -eq 0 ]; then
    echo -e "${GREEN}ALL $TOTAL TESTS PASSED — 100% SUCCESS${NC}"
    exit 0
else
    echo -e "${RED}$FAILED OF $TOTAL TESTS FAILED${NC}"
    exit 1
fi
